# Form implementation generated from reading ui file 'Access_UI.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_access_MainWindow(object):
    def setupUi(self, access_MainWindow):
        access_MainWindow.setObjectName("access_MainWindow")
        access_MainWindow.resize(1280, 720)
        access_MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        access_MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        access_MainWindow.setStyleSheet("background-color: rgb(180, 43, 29);")
        self.access_centralwidget = QtWidgets.QWidget(parent=access_MainWindow)
        self.access_centralwidget.setObjectName("access_centralwidget")
        self.access_stackedWidget = QtWidgets.QStackedWidget(parent=self.access_centralwidget)
        self.access_stackedWidget.setGeometry(QtCore.QRect(640, -21, 640, 741))
        self.access_stackedWidget.setMinimumSize(QtCore.QSize(640, 741))
        self.access_stackedWidget.setMaximumSize(QtCore.QSize(640, 741))
        self.access_stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.access_stackedWidget.setObjectName("access_stackedWidget")
        self.access_page_login = QtWidgets.QWidget()
        self.access_page_login.setObjectName("access_page_login")
        self.accessLogin_label_Login = QtWidgets.QLabel(parent=self.access_page_login)
        self.accessLogin_label_Login.setGeometry(QtCore.QRect(0, 70, 641, 111))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(48)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.accessLogin_label_Login.setFont(font)
        self.accessLogin_label_Login.setStyleSheet("QLabel {\n"
"    color: rgb(0, 0, 0);\n"
"    font:  48pt \"Segoe UI\", \"Arial\", sans-serif;\n"
"    letter-spacing: 0.5px;\n"
"}\n"
"")
        self.accessLogin_label_Login.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.accessLogin_label_Login.setObjectName("accessLogin_label_Login")
        self.accessLogin_pushButton_createAcc = QtWidgets.QPushButton(parent=self.access_page_login)
        self.accessLogin_pushButton_createAcc.setGeometry(QtCore.QRect(170, 600, 316, 40))
        self.accessLogin_pushButton_createAcc.setMinimumSize(QtCore.QSize(316, 40))
        self.accessLogin_pushButton_createAcc.setMaximumSize(QtCore.QSize(316, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.accessLogin_pushButton_createAcc.setFont(font)
        self.accessLogin_pushButton_createAcc.setStyleSheet("QPushButton {\n"
"    background-color: #D9D9D9;\n"
"    color: #333333;\n"
"    border: none;\n"
"    border-radius: 0px;  /* Sharp corners for modern flat design */\n"
"    font: 12pt \"Segoe UI\", \"Arial\", sans-serif;\n"
"    padding: 8px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #CFCFCF;  /* Slightly darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #BFBFBF;  /* Even darker on press */\n"
"}")
        self.accessLogin_pushButton_createAcc.setObjectName("accessLogin_pushButton_createAcc")
        self.accessLogin_label_password = QtWidgets.QLabel(parent=self.access_page_login)
        self.accessLogin_label_password.setGeometry(QtCore.QRect(170, 310, 311, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.accessLogin_label_password.setFont(font)
        self.accessLogin_label_password.setObjectName("accessLogin_label_password")
        self.accessLogin_lineEdit_username = QtWidgets.QLineEdit(parent=self.access_page_login)
        self.accessLogin_lineEdit_username.setGeometry(QtCore.QRect(170, 240, 316, 40))
        self.accessLogin_lineEdit_username.setMinimumSize(QtCore.QSize(316, 40))
        self.accessLogin_lineEdit_username.setMaximumSize(QtCore.QSize(316, 40))
        self.accessLogin_lineEdit_username.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(217, 217, 217); \n"
"    border:false;\n"
"text-align: left; padding-left: 10px;\n"
"    font: 12pt \"Arial\";\n"
"}\n"
"")
        self.accessLogin_lineEdit_username.setText("")
        self.accessLogin_lineEdit_username.setObjectName("accessLogin_lineEdit_username")
        self.accessLogin_lineEdit_password = QtWidgets.QLineEdit(parent=self.access_page_login)
        self.accessLogin_lineEdit_password.setGeometry(QtCore.QRect(170, 340, 316, 40))
        self.accessLogin_lineEdit_password.setMinimumSize(QtCore.QSize(316, 40))
        self.accessLogin_lineEdit_password.setMaximumSize(QtCore.QSize(316, 40))
        self.accessLogin_lineEdit_password.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(217, 217, 217); \n"
"    border:false;\n"
"text-align: left; padding-left: 10px;\n"
"    font: 12pt \"Arial\";\n"
"}\n"
"")
        self.accessLogin_lineEdit_password.setObjectName("accessLogin_lineEdit_password")
        self.accessLogin_comboBox_custSeller = QtWidgets.QComboBox(parent=self.access_page_login)
        self.accessLogin_comboBox_custSeller.setGeometry(QtCore.QRect(170, 410, 316, 40))
        self.accessLogin_comboBox_custSeller.setMinimumSize(QtCore.QSize(316, 40))
        self.accessLogin_comboBox_custSeller.setMaximumSize(QtCore.QSize(316, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.accessLogin_comboBox_custSeller.setFont(font)
        self.accessLogin_comboBox_custSeller.setStyleSheet("\n"
"QComboBox {\n"
"    background-color: rgb(217, 217, 217); \n"
"    color: #333333;\n"
"    border: 1px solid #CCCCCC;\n"
"    \n"
"    text-align: left; padding-left: 10px;\n"
"    font: 12pt \"Segoe UI\", \"Arial\", sans-serif;\n"
"}\n"
"\n"
"/* Optional: highlight on focus */\n"
"QComboBox:focus {\n"
"    border: 1px solid #0078D7;\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"")
        self.accessLogin_comboBox_custSeller.setObjectName("accessLogin_comboBox_custSeller")
        self.accessLogin_comboBox_custSeller.addItem("")
        self.accessLogin_comboBox_custSeller.addItem("")
        self.accessLogin_label_Error = QtWidgets.QLabel(parent=self.access_page_login)
        self.accessLogin_label_Error.setGeometry(QtCore.QRect(0, 680, 641, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.accessLogin_label_Error.setFont(font)
        self.accessLogin_label_Error.setStyleSheet("QLabel {\n"
"    color: rgb(180, 43, 29)\n"
"}")
        self.accessLogin_label_Error.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.accessLogin_label_Error.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.accessLogin_label_Error.setObjectName("accessLogin_label_Error")
        self.accessLogin_label_username = QtWidgets.QLabel(parent=self.access_page_login)
        self.accessLogin_label_username.setGeometry(QtCore.QRect(170, 210, 311, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.accessLogin_label_username.setFont(font)
        self.accessLogin_label_username.setObjectName("accessLogin_label_username")
        self.accessLogin_pushButton_login = QtWidgets.QPushButton(parent=self.access_page_login)
        self.accessLogin_pushButton_login.setGeometry(QtCore.QRect(170, 490, 316, 40))
        self.accessLogin_pushButton_login.setMinimumSize(QtCore.QSize(316, 40))
        self.accessLogin_pushButton_login.setMaximumSize(QtCore.QSize(316, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.accessLogin_pushButton_login.setFont(font)
        self.accessLogin_pushButton_login.setStyleSheet("QPushButton {\n"
"    background-color: #D9D9D9;\n"
"    color: #333333;\n"
"    border: none;\n"
"    border-radius: 0px;  /* Sharp corners for modern flat design */\n"
"    font: 12pt \"Segoe UI\", \"Arial\", sans-serif;\n"
"    padding: 8px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #CFCFCF;  /* Slightly darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #BFBFBF;  /* Even darker on press */\n"
"}\n"
"")
        self.accessLogin_pushButton_login.setObjectName("accessLogin_pushButton_login")
        self.accessLogin_line_login = QtWidgets.QFrame(parent=self.access_page_login)
        self.accessLogin_line_login.setGeometry(QtCore.QRect(170, 560, 311, 16))
        self.accessLogin_line_login.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.accessLogin_line_login.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.accessLogin_line_login.setObjectName("accessLogin_line_login")
        self.access_stackedWidget.addWidget(self.access_page_login)
        self.access_page_signup = QtWidgets.QWidget()
        self.access_page_signup.setObjectName("access_page_signup")
        self.accessSignup_lineEdit_username = QtWidgets.QLineEdit(parent=self.access_page_signup)
        self.accessSignup_lineEdit_username.setGeometry(QtCore.QRect(170, 170, 316, 30))
        self.accessSignup_lineEdit_username.setMinimumSize(QtCore.QSize(316, 30))
        self.accessSignup_lineEdit_username.setMaximumSize(QtCore.QSize(316, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.accessSignup_lineEdit_username.setFont(font)
        self.accessSignup_lineEdit_username.setStyleSheet("QLineEdit{\n"
"text-align: left; padding-left: 10px;\n"
"    background-color: rgb(217, 217, 217); \n"
"    border:false;\n"
"    font: 10pt \"Arial\";\n"
"}\n"
"")
        self.accessSignup_lineEdit_username.setObjectName("accessSignup_lineEdit_username")
        self.accessSignup_label_SignUp = QtWidgets.QLabel(parent=self.access_page_signup)
        self.accessSignup_label_SignUp.setGeometry(QtCore.QRect(0, 30, 641, 111))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(32)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.accessSignup_label_SignUp.setFont(font)
        self.accessSignup_label_SignUp.setStyleSheet("QLabel {\n"
"    color: rgb(0, 0, 0);\n"
"    font:  32pt \"Segoe UI\", \"Arial\", sans-serif;\n"
"    letter-spacing: 0.5px;\n"
"}\n"
"")
        self.accessSignup_label_SignUp.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.accessSignup_label_SignUp.setObjectName("accessSignup_label_SignUp")
        self.accessSignup_comboBox_custSeller = QtWidgets.QComboBox(parent=self.access_page_signup)
        self.accessSignup_comboBox_custSeller.setGeometry(QtCore.QRect(170, 500, 316, 30))
        self.accessSignup_comboBox_custSeller.setMinimumSize(QtCore.QSize(316, 30))
        self.accessSignup_comboBox_custSeller.setMaximumSize(QtCore.QSize(316, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.accessSignup_comboBox_custSeller.setFont(font)
        self.accessSignup_comboBox_custSeller.setStyleSheet("QComboBox{\n"
"    background-color: rgb(217, 217, 217); \n"
"    border:false;\n"
"text-align: left; padding-left: 10px;\n"
"}\n"
"")
        self.accessSignup_comboBox_custSeller.setObjectName("accessSignup_comboBox_custSeller")
        self.accessSignup_comboBox_custSeller.addItem("")
        self.accessSignup_comboBox_custSeller.addItem("")
        self.accessSignup_line_signup = QtWidgets.QFrame(parent=self.access_page_signup)
        self.accessSignup_line_signup.setGeometry(QtCore.QRect(170, 610, 311, 16))
        self.accessSignup_line_signup.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.accessSignup_line_signup.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.accessSignup_line_signup.setObjectName("accessSignup_line_signup")
        self.accessSignup_pushButton_logintoAcc = QtWidgets.QPushButton(parent=self.access_page_signup)
        self.accessSignup_pushButton_logintoAcc.setGeometry(QtCore.QRect(170, 630, 316, 35))
        self.accessSignup_pushButton_logintoAcc.setMinimumSize(QtCore.QSize(316, 35))
        self.accessSignup_pushButton_logintoAcc.setMaximumSize(QtCore.QSize(316, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.accessSignup_pushButton_logintoAcc.setFont(font)
        self.accessSignup_pushButton_logintoAcc.setStyleSheet("QPushButton {\n"
"    background-color: #D9D9D9;\n"
"    color: #333333;\n"
"    border: none;\n"
"    border-radius: 0px;  /* Sharp corners for modern flat design */\n"
"    font: 9pt \"Segoe UI\", \"Arial\", sans-serif;\n"
"    padding: 8px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #CFCFCF;  /* Slightly darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #BFBFBF;  /* Even darker on press */\n"
"}")
        self.accessSignup_pushButton_logintoAcc.setObjectName("accessSignup_pushButton_logintoAcc")
        self.accessSignup_label_Error = QtWidgets.QLabel(parent=self.access_page_signup)
        self.accessSignup_label_Error.setGeometry(QtCore.QRect(0, 690, 641, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.accessSignup_label_Error.setFont(font)
        self.accessSignup_label_Error.setStyleSheet("QLabel {\n"
"    color: rgb(180, 43, 29)\n"
"}")
        self.accessSignup_label_Error.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.accessSignup_label_Error.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.accessSignup_label_Error.setObjectName("accessSignup_label_Error")
        self.accessSignup_label_username = QtWidgets.QLabel(parent=self.access_page_signup)
        self.accessSignup_label_username.setGeometry(QtCore.QRect(170, 140, 311, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.accessSignup_label_username.setFont(font)
        self.accessSignup_label_username.setObjectName("accessSignup_label_username")
        self.accessSignup_pushButton_signup = QtWidgets.QPushButton(parent=self.access_page_signup)
        self.accessSignup_pushButton_signup.setGeometry(QtCore.QRect(170, 570, 316, 35))
        self.accessSignup_pushButton_signup.setMinimumSize(QtCore.QSize(316, 35))
        self.accessSignup_pushButton_signup.setMaximumSize(QtCore.QSize(316, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.accessSignup_pushButton_signup.setFont(font)
        self.accessSignup_pushButton_signup.setStyleSheet("QPushButton {\n"
"    background-color: #D9D9D9;\n"
"    color: #333333;\n"
"    border: none;\n"
"    border-radius: 0px;  /* Sharp corners for modern flat design */\n"
"    font: 9pt \"Segoe UI\", \"Arial\", sans-serif;\n"
"    padding: 8px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #CFCFCF;  /* Slightly darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #BFBFBF;  /* Even darker on press */\n"
"}")
        self.accessSignup_pushButton_signup.setObjectName("accessSignup_pushButton_signup")
        self.accessSignup_lineEdit_password = QtWidgets.QLineEdit(parent=self.access_page_signup)
        self.accessSignup_lineEdit_password.setGeometry(QtCore.QRect(170, 240, 316, 30))
        self.accessSignup_lineEdit_password.setMinimumSize(QtCore.QSize(316, 30))
        self.accessSignup_lineEdit_password.setMaximumSize(QtCore.QSize(316, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.accessSignup_lineEdit_password.setFont(font)
        self.accessSignup_lineEdit_password.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(217, 217, 217); \n"
"    border:false;\n"
"    font: 10pt \"Arial\";\n"
"text-align: left; padding-left: 10px;\n"
"}\n"
"")
        self.accessSignup_lineEdit_password.setObjectName("accessSignup_lineEdit_password")
        self.accessSignup_label_password = QtWidgets.QLabel(parent=self.access_page_signup)
        self.accessSignup_label_password.setGeometry(QtCore.QRect(170, 210, 311, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.accessSignup_label_password.setFont(font)
        self.accessSignup_label_password.setObjectName("accessSignup_label_password")
        self.accessSignup_lineEdit_fullname = QtWidgets.QLineEdit(parent=self.access_page_signup)
        self.accessSignup_lineEdit_fullname.setGeometry(QtCore.QRect(170, 310, 316, 30))
        self.accessSignup_lineEdit_fullname.setMinimumSize(QtCore.QSize(316, 30))
        self.accessSignup_lineEdit_fullname.setMaximumSize(QtCore.QSize(316, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.accessSignup_lineEdit_fullname.setFont(font)
        self.accessSignup_lineEdit_fullname.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(217, 217, 217); \n"
"    border:false;\n"
"    font: 10pt \"Arial\";\n"
"text-align: left; padding-left: 10px;\n"
"}\n"
"")
        self.accessSignup_lineEdit_fullname.setObjectName("accessSignup_lineEdit_fullname")
        self.accessSignup_label_fullname = QtWidgets.QLabel(parent=self.access_page_signup)
        self.accessSignup_label_fullname.setGeometry(QtCore.QRect(170, 280, 311, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.accessSignup_label_fullname.setFont(font)
        self.accessSignup_label_fullname.setObjectName("accessSignup_label_fullname")
        self.accessSignup_lineEdit_address = QtWidgets.QLineEdit(parent=self.access_page_signup)
        self.accessSignup_lineEdit_address.setGeometry(QtCore.QRect(170, 450, 316, 30))
        self.accessSignup_lineEdit_address.setMinimumSize(QtCore.QSize(316, 30))
        self.accessSignup_lineEdit_address.setMaximumSize(QtCore.QSize(316, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.accessSignup_lineEdit_address.setFont(font)
        self.accessSignup_lineEdit_address.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(217, 217, 217); \n"
"    border:false;\n"
"    font: 10pt \"Arial\";\n"
"text-align: left; padding-left: 10px;\n"
"}\n"
"")
        self.accessSignup_lineEdit_address.setText("")
        self.accessSignup_lineEdit_address.setObjectName("accessSignup_lineEdit_address")
        self.accessSignup_label_number = QtWidgets.QLabel(parent=self.access_page_signup)
        self.accessSignup_label_number.setGeometry(QtCore.QRect(170, 350, 311, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.accessSignup_label_number.setFont(font)
        self.accessSignup_label_number.setObjectName("accessSignup_label_number")
        self.accessSignup_label_address = QtWidgets.QLabel(parent=self.access_page_signup)
        self.accessSignup_label_address.setGeometry(QtCore.QRect(170, 420, 311, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.accessSignup_label_address.setFont(font)
        self.accessSignup_label_address.setObjectName("accessSignup_label_address")
        self.accessSignup_lineEdit_number = QtWidgets.QLineEdit(parent=self.access_page_signup)
        self.accessSignup_lineEdit_number.setGeometry(QtCore.QRect(170, 380, 316, 30))
        self.accessSignup_lineEdit_number.setMinimumSize(QtCore.QSize(316, 30))
        self.accessSignup_lineEdit_number.setMaximumSize(QtCore.QSize(316, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.accessSignup_lineEdit_number.setFont(font)
        self.accessSignup_lineEdit_number.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(217, 217, 217); \n"
"    border:false;\n"
"    font: 10pt \"Arial\";\n"
"text-align: left; padding-left: 10px;\n"
"}\n"
"")
        self.accessSignup_lineEdit_number.setObjectName("accessSignup_lineEdit_number")
        self.accessLogin_lineEdit_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.accessSignup_lineEdit_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.access_stackedWidget.addWidget(self.access_page_signup)
        access_MainWindow.setCentralWidget(self.access_centralwidget)

        self.retranslateUi(access_MainWindow)
        self.access_stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(access_MainWindow)

    def retranslateUi(self, access_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        access_MainWindow.setWindowTitle(_translate("access_MainWindow", "Ngyopify : Login /  Sign Up"))
        self.accessLogin_label_Login.setText(_translate("access_MainWindow", "Log In"))
        self.accessLogin_label_Login.setProperty("aaaa", _translate("access_MainWindow", "sa"))
        self.accessLogin_pushButton_createAcc.setText(_translate("access_MainWindow", "Create Account"))
        self.accessLogin_label_password.setText(_translate("access_MainWindow", "Password"))
        self.accessLogin_comboBox_custSeller.setItemText(0, _translate("access_MainWindow", "Customer"))
        self.accessLogin_comboBox_custSeller.setItemText(1, _translate("access_MainWindow", "Seller"))
        self.accessLogin_label_Error.setText(_translate("access_MainWindow", ""))
        self.accessLogin_label_Error.setProperty("aaaa", _translate("access_MainWindow", "sa"))
        self.accessLogin_label_username.setText(_translate("access_MainWindow", "Username"))
        self.accessLogin_pushButton_login.setText(_translate("access_MainWindow", "Login"))
        self.accessSignup_label_SignUp.setText(_translate("access_MainWindow", "Sign Up"))
        self.accessSignup_label_SignUp.setProperty("aaaa", _translate("access_MainWindow", "sa"))
        self.accessSignup_comboBox_custSeller.setItemText(0, _translate("access_MainWindow", "Customer"))
        self.accessSignup_comboBox_custSeller.setItemText(1, _translate("access_MainWindow", "Seller"))
        self.accessSignup_pushButton_logintoAcc.setText(_translate("access_MainWindow", "Log into Account"))
        self.accessSignup_label_Error.setText(_translate("access_MainWindow", ""))
        self.accessSignup_label_Error.setProperty("aaaa", _translate("access_MainWindow", "sa"))
        self.accessSignup_label_username.setText(_translate("access_MainWindow", "Username"))
        self.accessSignup_pushButton_signup.setText(_translate("access_MainWindow", "Sign Up"))
        self.accessSignup_label_password.setText(_translate("access_MainWindow", "Password"))
        self.accessSignup_label_fullname.setText(_translate("access_MainWindow", "Full Name"))
        self.accessSignup_label_number.setText(_translate("access_MainWindow", "Contact Number"))
        self.accessSignup_label_address.setText(_translate("access_MainWindow", "Address"))
