# Form implementation generated from reading ui file 'Addproduct_UI.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_addProduct_MainWindow(object):
    def setupUi(self, addProduct_MainWindow):
        addProduct_MainWindow.setObjectName("addProduct_MainWindow")
        addProduct_MainWindow.resize(640, 720)
        addProduct_MainWindow.setMinimumSize(QtCore.QSize(640, 720))
        addProduct_MainWindow.setMaximumSize(QtCore.QSize(640, 720))
        addProduct_MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.addProduct_centralwidget = QtWidgets.QWidget(parent=addProduct_MainWindow)
        self.addProduct_centralwidget.setObjectName("addProduct_centralwidget")
        self.addProduct_widget_header = QtWidgets.QWidget(parent=self.addProduct_centralwidget)
        self.addProduct_widget_header.setGeometry(QtCore.QRect(0, 0, 640, 88))
        self.addProduct_widget_header.setMinimumSize(QtCore.QSize(640, 88))
        self.addProduct_widget_header.setMaximumSize(QtCore.QSize(640, 88))
        self.addProduct_widget_header.setStyleSheet("QWidget{\n"
"     background-color: rgb(180, 43, 29);\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color:  rgb(255, 255, 255);\n"
"    color: #333;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    font: bold 8pt \"Segoe UI\", \"Arial\";\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e6e6e6;\n"
"    border: 1px solid #bbb;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #dcdcdc;\n"
"    border: 1px solid #aaa;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"    font: 400 20pt \"Segoe UI\", \"Arial\", sans-serif;\n"
"    letter-spacing: 0.5px;\n"
"    padding: 4px 0;\n"
"}")
        self.addProduct_widget_header.setObjectName("addProduct_widget_header")
        self.addProduct_pushButton_back = QtWidgets.QPushButton(parent=self.addProduct_widget_header)
        self.addProduct_pushButton_back.setGeometry(QtCore.QRect(30, 30, 61, 31))
        self.addProduct_pushButton_back.setFlat(False)
        self.addProduct_pushButton_back.setObjectName("addProduct_pushButton_back")
        self.addProduct_label_addProduct = QtWidgets.QLabel(parent=self.addProduct_widget_header)
        self.addProduct_label_addProduct.setGeometry(QtCore.QRect(180, 10, 281, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.addProduct_label_addProduct.setFont(font)
        self.addProduct_label_addProduct.setStyleSheet("")
        self.addProduct_label_addProduct.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.addProduct_label_addProduct.setObjectName("addProduct_label_addProduct")
        self.addProduct_widget_input = QtWidgets.QWidget(parent=self.addProduct_centralwidget)
        self.addProduct_widget_input.setGeometry(QtCore.QRect(60, 130, 521, 451))
        self.addProduct_widget_input.setStyleSheet("QLabel {\n"
"    color: rgb(0, 0, 0);         /* Dark neutral text */\n"
"    font: 12pt \"Segoe UI\", \"Arial\", sans-serif;  /* Clean, modern font */\n"
"    letter-spacing: 0.2px;       /* Subtle spacing for readability */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #F0F0F0;\n"
"    color: #333333;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 4px;\n"
"    padding: 6px 10px;\n"
"    font: 10pt \"Segoe UI\", \"Arial\", sans-serif;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: #F0F0F0;\n"
"    color: #333333;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 4px;\n"
"    text-align: left; padding-left: 10px;\n"
"    font: 12pt \"Segoe UI\", \"Arial\", sans-serif;\n"
"}\n"
"\n"
"/* Optional: highlight on focus */\n"
"QComboBox:focus {\n"
"    border: 1px solid #0078D7;\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #D9D9D9;         /* Light neutral gray */\n"
"    color: #333333;                    /* Dark text for contrast */\n"
"    border: none;\n"
"    border-radius: 6px;                /* You can change to 0px for square corners */\n"
"    font: 9pt \"Segoe UI\", \"Arial\", sans-serif;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #CFCFCF;         /* Slightly darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #BFBFBF;         /* Darker when pressed */\n"
"}\n"
"\n"
"")
        self.addProduct_widget_input.setObjectName("addProduct_widget_input")
        self.addProduct_lineEdit_productName = QtWidgets.QLineEdit(parent=self.addProduct_widget_input)
        self.addProduct_lineEdit_productName.setGeometry(QtCore.QRect(150, 20, 341, 40))
        self.addProduct_lineEdit_productName.setMinimumSize(QtCore.QSize(341, 40))
        self.addProduct_lineEdit_productName.setMaximumSize(QtCore.QSize(355, 40))
        self.addProduct_lineEdit_productName.setStyleSheet("")
        self.addProduct_lineEdit_productName.setText("")
        self.addProduct_lineEdit_productName.setObjectName("addProduct_lineEdit_productName")
        self.addProduct_label_productName = QtWidgets.QLabel(parent=self.addProduct_widget_input)
        self.addProduct_label_productName.setGeometry(QtCore.QRect(0, 30, 121, 21))
        self.addProduct_label_productName.setMinimumSize(QtCore.QSize(121, 21))
        self.addProduct_label_productName.setMaximumSize(QtCore.QSize(121, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.addProduct_label_productName.setFont(font)
        self.addProduct_label_productName.setStyleSheet("QLabel {\n"
"     color: #333333;          /* Dark neutral text */\n"
"    font: 12pt \"Segoe UI\", \"Arial\", sans-serif;  /* Clean, modern font */\n"
"    letter-spacing: 0.2px;       /* Subtle spacing for readability */\n"
"}")
        self.addProduct_label_productName.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.addProduct_label_productName.setObjectName("addProduct_label_productName")
        self.addProduct_label_category = QtWidgets.QLabel(parent=self.addProduct_widget_input)
        self.addProduct_label_category.setGeometry(QtCore.QRect(0, 130, 121, 21))
        self.addProduct_label_category.setMinimumSize(QtCore.QSize(121, 21))
        self.addProduct_label_category.setMaximumSize(QtCore.QSize(121, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.addProduct_label_category.setFont(font)
        self.addProduct_label_category.setStyleSheet("QLabel {\n"
"     color: #333333;          /* Dark neutral text */\n"
"    font: 12pt \"Segoe UI\", \"Arial\", sans-serif;  /* Clean, modern font */\n"
"    letter-spacing: 0.2px;       /* Subtle spacing for readability */\n"
"}")
        self.addProduct_label_category.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.addProduct_label_category.setObjectName("addProduct_label_category")
        self.addProduct_label_price = QtWidgets.QLabel(parent=self.addProduct_widget_input)
        self.addProduct_label_price.setGeometry(QtCore.QRect(0, 220, 121, 21))
        self.addProduct_label_price.setMinimumSize(QtCore.QSize(121, 21))
        self.addProduct_label_price.setMaximumSize(QtCore.QSize(121, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.addProduct_label_price.setFont(font)
        self.addProduct_label_price.setStyleSheet("QLabel {\n"
"     color: #333333;          /* Dark neutral text */\n"
"    font: 12pt \"Segoe UI\", \"Arial\", sans-serif;  /* Clean, modern font */\n"
"    letter-spacing: 0.2px;       /* Subtle spacing for readability */\n"
"}")
        self.addProduct_label_price.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.addProduct_label_price.setObjectName("addProduct_label_price")
        self.addProduct_lineEdit_productImage = QtWidgets.QLineEdit(parent=self.addProduct_widget_input)
        self.addProduct_lineEdit_productImage.setGeometry(QtCore.QRect(150, 390, 231, 40))
        self.addProduct_lineEdit_productImage.setMinimumSize(QtCore.QSize(231, 40))
        self.addProduct_lineEdit_productImage.setMaximumSize(QtCore.QSize(355, 40))
        self.addProduct_lineEdit_productImage.setStyleSheet("")
        self.addProduct_lineEdit_productImage.setText("")
        self.addProduct_lineEdit_productImage.setReadOnly(True)
        self.addProduct_lineEdit_productImage.setObjectName("addProduct_lineEdit_productImage")
        self.addProduct_label_productimage = QtWidgets.QLabel(parent=self.addProduct_widget_input)
        self.addProduct_label_productimage.setGeometry(QtCore.QRect(0, 400, 121, 21))
        self.addProduct_label_productimage.setMinimumSize(QtCore.QSize(121, 21))
        self.addProduct_label_productimage.setMaximumSize(QtCore.QSize(121, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.addProduct_label_productimage.setFont(font)
        self.addProduct_label_productimage.setStyleSheet("QLabel {\n"
"     color: #333333;          /* Dark neutral text */\n"
"    font: 12pt \"Segoe UI\", \"Arial\", sans-serif;  /* Clean, modern font */\n"
"    letter-spacing: 0.2px;       /* Subtle spacing for readability */\n"
"}")
        self.addProduct_label_productimage.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.addProduct_label_productimage.setObjectName("addProduct_label_productimage")
        self.addProduct_label_stock = QtWidgets.QLabel(parent=self.addProduct_widget_input)
        self.addProduct_label_stock.setGeometry(QtCore.QRect(0, 320, 121, 21))
        self.addProduct_label_stock.setMinimumSize(QtCore.QSize(121, 21))
        self.addProduct_label_stock.setMaximumSize(QtCore.QSize(121, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.addProduct_label_stock.setFont(font)
        self.addProduct_label_stock.setStyleSheet("QLabel {\n"
"     color: #333333;          /* Dark neutral text */\n"
"    font: 12pt \"Segoe UI\", \"Arial\", sans-serif;  /* Clean, modern font */\n"
"    letter-spacing: 0.2px;       /* Subtle spacing for readability */\n"
"}")
        self.addProduct_label_stock.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.addProduct_label_stock.setObjectName("addProduct_label_stock")
        self.addProduct_pushButton_browseFiles = QtWidgets.QPushButton(parent=self.addProduct_widget_input)
        self.addProduct_pushButton_browseFiles.setGeometry(QtCore.QRect(390, 390, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.addProduct_pushButton_browseFiles.setFont(font)
        self.addProduct_pushButton_browseFiles.setStyleSheet("")
        self.addProduct_pushButton_browseFiles.setObjectName("addProduct_pushButton_browseFiles")
        self.addProduct_lineEdit_price = QtWidgets.QLineEdit(parent=self.addProduct_widget_input)
        self.addProduct_lineEdit_price.setGeometry(QtCore.QRect(150, 210, 341, 40))
        self.addProduct_lineEdit_price.setMinimumSize(QtCore.QSize(341, 40))
        self.addProduct_lineEdit_price.setMaximumSize(QtCore.QSize(355, 40))
        self.addProduct_lineEdit_price.setStyleSheet("")
        self.addProduct_lineEdit_price.setText("")
        self.addProduct_lineEdit_price.setObjectName("addProduct_lineEdit_price")
        self.addProduct_lineEdit_stock = QtWidgets.QLineEdit(parent=self.addProduct_widget_input)
        self.addProduct_lineEdit_stock.setGeometry(QtCore.QRect(150, 310, 341, 40))
        self.addProduct_lineEdit_stock.setMinimumSize(QtCore.QSize(341, 40))
        self.addProduct_lineEdit_stock.setMaximumSize(QtCore.QSize(355, 40))
        self.addProduct_lineEdit_stock.setStyleSheet("")
        self.addProduct_lineEdit_stock.setText("")
        self.addProduct_lineEdit_stock.setObjectName("addProduct_lineEdit_stock")
        self.addProduct_comboBox_category = QtWidgets.QComboBox(parent=self.addProduct_widget_input)
        self.addProduct_comboBox_category.setGeometry(QtCore.QRect(150, 120, 341, 41))
        self.addProduct_comboBox_category.setObjectName("addProduct_comboBox_category")
        self.addProduct_comboBox_category.addItem("")
        self.addProduct_comboBox_category.addItem("")
        self.addProduct_comboBox_category.addItem("")
        self.addProduct_comboBox_category.addItem("")
        self.addProduct_comboBox_category.addItem("")
        self.addProduct_comboBox_category.addItem("")
        self.addProduct_comboBox_category.addItem("")
        self.addProduct_pushButton_savePublish = QtWidgets.QPushButton(parent=self.addProduct_centralwidget)
        self.addProduct_pushButton_savePublish.setGeometry(QtCore.QRect(320, 620, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.addProduct_pushButton_savePublish.setFont(font)
        self.addProduct_pushButton_savePublish.setStyleSheet("QPushButton {\n"
"    background-color: #B42B1D;         /* Flat red */\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 6px;                /* Optional: remove if you want sharp corners */\n"
"    font: bold 9pt \"Segoe UI\", \"Arial\", sans-serif;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #a1281a;         /* Slightly darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #8c2116;         /* Even darker when pressed */\n"
"}")
        self.addProduct_pushButton_savePublish.setObjectName("addProduct_pushButton_savePublish")
        self.addProduct_label_Error = QtWidgets.QLabel(parent=self.addProduct_centralwidget)
        self.addProduct_label_Error.setGeometry(QtCore.QRect(80, 630, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.addProduct_label_Error.setFont(font)
        self.addProduct_label_Error.setStyleSheet("QLabel {\n"
"    color: rgb(180, 43, 29);\n"
"    font: 10pt \"Segoe UI\", \"Arial\", sans-serif;  /* Clean, modern font */\n"
"    letter-spacing: 0.2px;       /* Subtle spacing for readability */\n"
"}")
        self.addProduct_label_Error.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.addProduct_label_Error.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.addProduct_label_Error.setObjectName("addProduct_label_Error")
        addProduct_MainWindow.setCentralWidget(self.addProduct_centralwidget)

        self.retranslateUi(addProduct_MainWindow)
        self.addProduct_comboBox_category.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(addProduct_MainWindow)

    def retranslateUi(self, addProduct_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        addProduct_MainWindow.setWindowTitle(_translate("addProduct_MainWindow", "Ngyopify : Add a New Product"))
        self.addProduct_pushButton_back.setText(_translate("addProduct_MainWindow", "Back"))
        self.addProduct_label_addProduct.setText(_translate("addProduct_MainWindow", "Add a New Product"))
        self.addProduct_label_addProduct.setProperty("aaaa", _translate("addProduct_MainWindow", "sa"))
        self.addProduct_label_productName.setText(_translate("addProduct_MainWindow", "Product Name"))
        self.addProduct_label_productName.setProperty("aaaa", _translate("addProduct_MainWindow", "sa"))
        self.addProduct_label_category.setText(_translate("addProduct_MainWindow", "Category"))
        self.addProduct_label_category.setProperty("aaaa", _translate("addProduct_MainWindow", "sa"))
        self.addProduct_label_price.setText(_translate("addProduct_MainWindow", "Price"))
        self.addProduct_label_price.setProperty("aaaa", _translate("addProduct_MainWindow", "sa"))
        self.addProduct_lineEdit_productImage.setPlaceholderText(_translate("addProduct_MainWindow", "Browse File to Upload"))
        self.addProduct_label_productimage.setText(_translate("addProduct_MainWindow", "Product Image"))
        self.addProduct_label_productimage.setProperty("aaaa", _translate("addProduct_MainWindow", "sa"))
        self.addProduct_label_stock.setText(_translate("addProduct_MainWindow", "Stock"))
        self.addProduct_label_stock.setProperty("aaaa", _translate("addProduct_MainWindow", "sa"))
        self.addProduct_pushButton_browseFiles.setText(_translate("addProduct_MainWindow", "Browse Files"))
        self.addProduct_comboBox_category.setCurrentText(_translate("addProduct_MainWindow", "Others"))
        self.addProduct_comboBox_category.setItemText(0, _translate("addProduct_MainWindow", "Books and Stationery"))
        self.addProduct_comboBox_category.setItemText(1, _translate("addProduct_MainWindow", "Clothing and Fashion"))
        self.addProduct_comboBox_category.setItemText(2, _translate("addProduct_MainWindow", "Electronics and Gadgets"))
        self.addProduct_comboBox_category.setItemText(3, _translate("addProduct_MainWindow", "Food and Snacks"))
        self.addProduct_comboBox_category.setItemText(4, _translate("addProduct_MainWindow", "Health and Beauty"))
        self.addProduct_comboBox_category.setItemText(5, _translate("addProduct_MainWindow", "Home and Living"))
        self.addProduct_comboBox_category.setItemText(6, _translate("addProduct_MainWindow", "Others"))
        self.addProduct_pushButton_savePublish.setText(_translate("addProduct_MainWindow", "Save and Publish"))
        self.addProduct_label_Error.setText(_translate("addProduct_MainWindow", ""))
        self.addProduct_label_Error.setProperty("aaaa", _translate("addProduct_MainWindow", "sa"))
