# Form implementation generated from reading ui file 'Confirm_UI.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_confirm_MainWindow(object):
    def setupUi(self, confirm_MainWindow):
        confirm_MainWindow.setObjectName("confirm_MainWindow")
        confirm_MainWindow.resize(640, 720)
        confirm_MainWindow.setMinimumSize(QtCore.QSize(640, 720))
        confirm_MainWindow.setMaximumSize(QtCore.QSize(640, 720))
        self.confirm_centralwidget = QtWidgets.QWidget(parent=confirm_MainWindow)
        self.confirm_centralwidget.setObjectName("confirm_centralwidget")
        self.confirm_widget_header = QtWidgets.QWidget(parent=self.confirm_centralwidget)
        self.confirm_widget_header.setGeometry(QtCore.QRect(0, 0, 640, 88))
        self.confirm_widget_header.setMinimumSize(QtCore.QSize(640, 88))
        self.confirm_widget_header.setMaximumSize(QtCore.QSize(640, 88))
        self.confirm_widget_header.setStyleSheet("QWidget{\n"
"     background-color: rgb(180, 43, 29);\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"    font: 400 20pt \"Segoe UI\", \"Arial\", sans-serif;\n"
"    letter-spacing: 0.5px;\n"
"    padding: 4px 0;\n"
"}")
        self.confirm_widget_header.setObjectName("confirm_widget_header")
        self.confirm_label_orderConfirmation = QtWidgets.QLabel(parent=self.confirm_widget_header)
        self.confirm_label_orderConfirmation.setGeometry(QtCore.QRect(180, 10, 281, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.confirm_label_orderConfirmation.setFont(font)
        self.confirm_label_orderConfirmation.setStyleSheet("")
        self.confirm_label_orderConfirmation.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.confirm_label_orderConfirmation.setObjectName("confirm_label_orderConfirmation")
        self.confirm_label_thankYou = QtWidgets.QLabel(parent=self.confirm_centralwidget)
        self.confirm_label_thankYou.setGeometry(QtCore.QRect(60, 140, 521, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.confirm_label_thankYou.setFont(font)
        self.confirm_label_thankYou.setStyleSheet("QLabel {\n"
"    color: rgb(180, 43, 29) ;        /* Dark neutral text */\n"
"    font: bold 24pt \"Segoe UI\", \"Arial\", sans-serif;  /* Clean, modern font */\n"
"    letter-spacing: 0.2px;       /* Subtle spacing for readability */\n"
"}")
        self.confirm_label_thankYou.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.confirm_label_thankYou.setObjectName("confirm_label_thankYou")
        self.confirm_pushButton_continueShopping = QtWidgets.QPushButton(parent=self.confirm_centralwidget)
        self.confirm_pushButton_continueShopping.setGeometry(QtCore.QRect(230, 630, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.confirm_pushButton_continueShopping.setFont(font)
        self.confirm_pushButton_continueShopping.setStyleSheet("QPushButton {\n"
"    background-color: #B42B1D;         /* Flat red */\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 6px;                /* Optional: remove if you want sharp corners */\n"
"    font: bold 9pt \"Segoe UI\", \"Arial\", sans-serif;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #a1281a;         /* Slightly darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #8c2116;         /* Even darker when pressed */\n"
"}")
        self.confirm_pushButton_continueShopping.setObjectName("confirm_pushButton_continueShopping")
        self.confirm_listWidget_list = QtWidgets.QListWidget(parent=self.confirm_centralwidget)
        self.confirm_listWidget_list.setGeometry(QtCore.QRect(110, 220, 421, 311))
        self.confirm_listWidget_list.setStyleSheet("QListWidget {\n"
"    background-color: #F9F9F9;\n"
"    color: #333333;\n"
"    border: 1px solid #CCCCCC;\n"
"    font: 9pt \"Segoe UI\", \"Arial\", sans-serif;\n"
"    padding: 4px;\n"
"    outline: none;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    padding: 6px 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: #0078D7;\n"
"    color: white;\n"
"}\n"
"")
        self.confirm_listWidget_list.setObjectName("confirm_listWidget_list")
        self.confirm_widget_total = QtWidgets.QWidget(parent=self.confirm_centralwidget)
        self.confirm_widget_total.setGeometry(QtCore.QRect(120, 560, 401, 41))
        self.confirm_widget_total.setObjectName("confirm_widget_total")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.confirm_widget_total)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.confirm_label_totalLabel = QtWidgets.QLabel(parent=self.confirm_widget_total)
        self.confirm_label_totalLabel.setMinimumSize(QtCore.QSize(150, 31))
        self.confirm_label_totalLabel.setMaximumSize(QtCore.QSize(150, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.confirm_label_totalLabel.setFont(font)
        self.confirm_label_totalLabel.setStyleSheet("QLabel {\n"
"    color: rgb(0, 0, 0);         /* Dark neutral text */\n"
"    font:  12pt \"Segoe UI\", \"Arial\", sans-serif;  /* Clean, modern font */\n"
"    letter-spacing: 0.2px;       /* Subtle spacing for readability */\n"
"}")
        self.confirm_label_totalLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.confirm_label_totalLabel.setObjectName("confirm_label_totalLabel")
        self.horizontalLayout.addWidget(self.confirm_label_totalLabel)
        self.confirm_label_totalValue = QtWidgets.QLabel(parent=self.confirm_widget_total)
        self.confirm_label_totalValue.setMinimumSize(QtCore.QSize(150, 31))
        self.confirm_label_totalValue.setMaximumSize(QtCore.QSize(150, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.confirm_label_totalValue.setFont(font)
        self.confirm_label_totalValue.setStyleSheet("QLabel {\n"
"    color: rgb(180, 43, 29);         /* Dark neutral text */\n"
"    font: bold 12pt \"Segoe UI\", \"Arial\", sans-serif;  /* Clean, modern font */\n"
"    letter-spacing: 0.2px;       /* Subtle spacing for readability */\n"
"}")
        self.confirm_label_totalValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.confirm_label_totalValue.setObjectName("confirm_label_totalValue")
        self.horizontalLayout.addWidget(self.confirm_label_totalValue)
        spacerItem1 = QtWidgets.QSpacerItem(29, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        confirm_MainWindow.setCentralWidget(self.confirm_centralwidget)

        self.retranslateUi(confirm_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(confirm_MainWindow)

    def retranslateUi(self, confirm_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        confirm_MainWindow.setWindowTitle(_translate("confirm_MainWindow", "Ngyopify : Order Confirmation"))
        self.confirm_label_orderConfirmation.setText(_translate("confirm_MainWindow", "Order Confirmation"))
        self.confirm_label_orderConfirmation.setProperty("aaaa", _translate("confirm_MainWindow", "sa"))
        self.confirm_label_thankYou.setText(_translate("confirm_MainWindow", "Thank you for your purchase!"))
        self.confirm_label_thankYou.setProperty("aaaa", _translate("confirm_MainWindow", "sa"))
        self.confirm_pushButton_continueShopping.setText(_translate("confirm_MainWindow", "Continue Shopping"))
        self.confirm_label_totalLabel.setText(_translate("confirm_MainWindow", "Total Amount  "))
        self.confirm_label_totalLabel.setProperty("aaaa", _translate("confirm_MainWindow", "sa"))
        self.confirm_label_totalValue.setText(_translate("confirm_MainWindow", "₱ 0000000.00"))
        self.confirm_label_totalValue.setProperty("aaaa", _translate("confirm_MainWindow", "sa"))
