# Form implementation generated from reading ui file 'Customer_UI.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QSizePolicy



class Ui_customer_MainWindow(object):
    def setupUi(self, customer_MainWindow):
        customer_MainWindow.setObjectName("customer_MainWindow")
        customer_MainWindow.resize(1280, 720)
        customer_MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        customer_MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        customer_MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.customer_centralwidget = QtWidgets.QWidget(parent=customer_MainWindow)
        self.customer_centralwidget.setObjectName("customer_centralwidget")
        self.customer_widget_header = QtWidgets.QWidget(parent=self.customer_centralwidget)
        self.customer_widget_header.setGeometry(QtCore.QRect(0, 0, 1280, 88))
        self.customer_widget_header.setMinimumSize(QtCore.QSize(1280, 88))
        self.customer_widget_header.setMaximumSize(QtCore.QSize(1280, 88))
        self.customer_widget_header.setStyleSheet("QWidget{\n"
"     background-color: rgb(180, 43, 29);\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color:  rgb(255, 255, 255);\n"
"    color: #333;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    font: bold 8pt \"Segoe UI\", \"Arial\";\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e6e6e6;\n"
"    border: 1px solid #bbb;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #dcdcdc;\n"
"    border: 1px solid #aaa;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"    font: 600 20pt \"Segoe UI\", \"Arial\", sans-serif;\n"
"    letter-spacing: 0.5px;\n"
"    padding: 4px 0;\n"
"}")
        self.customer_widget_header.setObjectName("customer_widget_header")
        self.customer_label_customerHomepage = QtWidgets.QLabel(parent=self.customer_widget_header)
        self.customer_label_customerHomepage.setGeometry(QtCore.QRect(440, 10, 401, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.customer_label_customerHomepage.setFont(font)
        self.customer_label_customerHomepage.setStyleSheet("")
        self.customer_label_customerHomepage.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.customer_label_customerHomepage.setObjectName("customer_label_customerHomepage")
        self.customer_pushButton_logOut = QtWidgets.QPushButton(parent=self.customer_widget_header)
        self.customer_pushButton_logOut.setGeometry(QtCore.QRect(1160, 30, 81, 31))
        self.customer_pushButton_logOut.setFlat(False)
        self.customer_pushButton_logOut.setObjectName("customer_pushButton_logOut")
        self.customer_pushButton_shoppingCart = QtWidgets.QPushButton(parent=self.customer_widget_header)
        self.customer_pushButton_shoppingCart.setGeometry(QtCore.QRect(920, 30, 111, 31))
        self.customer_pushButton_shoppingCart.setFlat(False)
        self.customer_pushButton_shoppingCart.setObjectName("customer_pushButton_shoppingCart")
        self.customer_pushButton_purchases = QtWidgets.QPushButton(parent=self.customer_widget_header)
        self.customer_pushButton_purchases.setGeometry(QtCore.QRect(1050, 30, 91, 31))
        self.customer_pushButton_purchases.setFlat(False)
        self.customer_pushButton_purchases.setObjectName("customer_pushButton_purchases")
        self.customer_widget_categories = QtWidgets.QWidget(parent=self.customer_centralwidget)
        self.customer_widget_categories.setGeometry(QtCore.QRect(80, 200, 299, 451))
        self.customer_widget_categories.setStyleSheet("QPushButton {\n"
"    background-color: rgb(217, 217, 217);\n"
"    color: #333;\n"
"    border: none;\n"
"    border-left: 4px solid transparent;\n"
"    font: 9pt \"Segoe UI\", \"Arial\";\n"
"    text-align: left;\n"
"    padding: 8px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(200, 200, 200);\n"
"    border-left: 4px solid #888;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(180, 180, 180);\n"
"    border-left: 4px solid #555;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: rgb(160, 160, 160);\n"
"    border-left: 4px solid #0078d7; /* Modern blue indicator for active state */\n"
"}\n"
"\n"
"// QWidget{ background-color: rgb(170, 255, 127); }\n"
"\n"
"")
        self.customer_widget_categories.setObjectName("customer_widget_categories")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.customer_widget_categories)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.customer_pushButton_booksStationary = QtWidgets.QPushButton(parent=self.customer_widget_categories)
        self.customer_pushButton_booksStationary.setMinimumSize(QtCore.QSize(281, 36))
        self.customer_pushButton_booksStationary.setMaximumSize(QtCore.QSize(281, 36))
        self.customer_pushButton_booksStationary.setCheckable(True)
        self.customer_pushButton_booksStationary.setAutoExclusive(True)
        self.customer_pushButton_booksStationary.setObjectName("customer_pushButton_booksStationary")
        self.verticalLayout.addWidget(self.customer_pushButton_booksStationary)
        spacerItem = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.customer_pushButton_clothingFashion = QtWidgets.QPushButton(parent=self.customer_widget_categories)
        self.customer_pushButton_clothingFashion.setMinimumSize(QtCore.QSize(281, 36))
        self.customer_pushButton_clothingFashion.setMaximumSize(QtCore.QSize(281, 36))
        self.customer_pushButton_clothingFashion.setCheckable(True)
        self.customer_pushButton_clothingFashion.setAutoExclusive(True)
        self.customer_pushButton_clothingFashion.setObjectName("customer_pushButton_clothingFashion")
        self.verticalLayout.addWidget(self.customer_pushButton_clothingFashion)
        spacerItem1 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.customer_pushButton_electronicsGadgets = QtWidgets.QPushButton(parent=self.customer_widget_categories)
        self.customer_pushButton_electronicsGadgets.setMinimumSize(QtCore.QSize(281, 36))
        self.customer_pushButton_electronicsGadgets.setMaximumSize(QtCore.QSize(281, 36))
        self.customer_pushButton_electronicsGadgets.setCheckable(True)
        self.customer_pushButton_electronicsGadgets.setAutoExclusive(True)
        self.customer_pushButton_electronicsGadgets.setObjectName("customer_pushButton_electronicsGadgets")
        self.verticalLayout.addWidget(self.customer_pushButton_electronicsGadgets)
        spacerItem2 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.customer_pushButton_foodSnacks = QtWidgets.QPushButton(parent=self.customer_widget_categories)
        self.customer_pushButton_foodSnacks.setMinimumSize(QtCore.QSize(281, 36))
        self.customer_pushButton_foodSnacks.setMaximumSize(QtCore.QSize(281, 36))
        self.customer_pushButton_foodSnacks.setCheckable(True)
        self.customer_pushButton_foodSnacks.setAutoExclusive(True)
        self.customer_pushButton_foodSnacks.setObjectName("customer_pushButton_foodSnacks")
        self.verticalLayout.addWidget(self.customer_pushButton_foodSnacks)
        spacerItem3 = QtWidgets.QSpacerItem(20, 16, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.customer_pushButton_healthBeauty = QtWidgets.QPushButton(parent=self.customer_widget_categories)
        self.customer_pushButton_healthBeauty.setMinimumSize(QtCore.QSize(281, 36))
        self.customer_pushButton_healthBeauty.setMaximumSize(QtCore.QSize(281, 36))
        self.customer_pushButton_healthBeauty.setCheckable(True)
        self.customer_pushButton_healthBeauty.setAutoExclusive(True)
        self.customer_pushButton_healthBeauty.setObjectName("customer_pushButton_healthBeauty")
        self.verticalLayout.addWidget(self.customer_pushButton_healthBeauty)
        spacerItem4 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.customer_pushButton_homeLiving = QtWidgets.QPushButton(parent=self.customer_widget_categories)
        self.customer_pushButton_homeLiving.setMinimumSize(QtCore.QSize(281, 36))
        self.customer_pushButton_homeLiving.setMaximumSize(QtCore.QSize(281, 36))
        self.customer_pushButton_homeLiving.setCheckable(True)
        self.customer_pushButton_homeLiving.setAutoExclusive(True)
        self.customer_pushButton_homeLiving.setObjectName("customer_pushButton_homeLiving")
        self.verticalLayout.addWidget(self.customer_pushButton_homeLiving)
        spacerItem5 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.customer_pushButton_others = QtWidgets.QPushButton(parent=self.customer_widget_categories)
        self.customer_pushButton_others.setMinimumSize(QtCore.QSize(281, 36))
        self.customer_pushButton_others.setMaximumSize(QtCore.QSize(281, 36))
        self.customer_pushButton_others.setCheckable(True)
        self.customer_pushButton_others.setAutoExclusive(True)
        self.customer_pushButton_others.setObjectName("customer_pushButton_others")
        self.verticalLayout.addWidget(self.customer_pushButton_others)
        self.customer_label_explore = QtWidgets.QLabel(parent=self.customer_centralwidget)
        self.customer_label_explore.setGeometry(QtCore.QRect(90, 130, 281, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.customer_label_explore.setFont(font)
        self.customer_label_explore.setStyleSheet("QLabel {\n"
"    color: #333333;              /* Dark neutral text */\n"
"    font: bold 28pt \"Segoe UI\", \"Arial\", sans-serif;  /* Clean, modern font */\n"
"    letter-spacing: 0.2px;       /* Subtle spacing for readability */\n"
"}")
        self.customer_label_explore.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.customer_label_explore.setObjectName("customer_label_explore")
        self.customer_widgets_products = QtWidgets.QWidget(parent=self.customer_centralwidget)
        self.customer_widgets_products.setGeometry(QtCore.QRect(420, 160, 781, 491))
        self.customer_widgets_products.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.customer_widgets_products.setObjectName("customer_widgets_products")
        self.customer_scrollArea_products = QtWidgets.QScrollArea(parent=self.customer_widgets_products)
        self.customer_scrollArea_products.setGeometry(QtCore.QRect(0, 0, 781, 491))
        self.customer_scrollArea_products.setWidgetResizable(True)
        self.customer_scrollArea_products.setObjectName("customer_scrollArea_products")
        self.customer_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.customer_scrollAreaWidgetContents.setSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        self.customer_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 779, 489))
        self.customer_scrollAreaWidgetContents.setObjectName("customer_scrollAreaWidgetContents")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.customer_scrollAreaWidgetContents)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 781, 491))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.customer_gridLayout_products = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.customer_gridLayout_products.setContentsMargins(0, 0, 0, 0)
        self.customer_gridLayout_products.setObjectName("customer_gridLayout_products")
        self.customer_scrollArea_products.setWidget(self.customer_scrollAreaWidgetContents)
        customer_MainWindow.setCentralWidget(self.customer_centralwidget)

        self.retranslateUi(customer_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(customer_MainWindow)

    def retranslateUi(self, customer_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        customer_MainWindow.setWindowTitle(_translate("customer_MainWindow", "Ngyopify : Customer Homepage"))
        self.customer_label_customerHomepage.setText(_translate("customer_MainWindow", "Ngyopify Customer Homepage"))
        self.customer_label_customerHomepage.setProperty("aaaa", _translate("customer_MainWindow", "sa"))
        self.customer_pushButton_logOut.setText(_translate("customer_MainWindow", "Log Out"))
        self.customer_pushButton_shoppingCart.setText(_translate("customer_MainWindow", "Shopping Cart"))
        self.customer_pushButton_purchases.setText(_translate("customer_MainWindow", "Purchases"))
        self.customer_pushButton_booksStationary.setText(_translate("customer_MainWindow", "Books and Stationery"))
        self.customer_pushButton_clothingFashion.setText(_translate("customer_MainWindow", "Clothing and Fashion"))
        self.customer_pushButton_electronicsGadgets.setText(_translate("customer_MainWindow", "Electronics and Gadgets"))
        self.customer_pushButton_foodSnacks.setText(_translate("customer_MainWindow", "Food and Snacks"))
        self.customer_pushButton_healthBeauty.setText(_translate("customer_MainWindow", "Health and Beauty"))
        self.customer_pushButton_homeLiving.setText(_translate("customer_MainWindow", "Home and Living"))
        self.customer_pushButton_others.setText(_translate("customer_MainWindow", "Others"))
        self.customer_label_explore.setText(_translate("customer_MainWindow", "Explore"))
        self.customer_label_explore.setProperty("aaaa", _translate("customer_MainWindow", "sa"))
