# Form implementation generated from reading ui file 'EditProduct_UI.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_editProduct_MainWindow(object):
    def setupUi(self, editProduct_MainWindow):
        editProduct_MainWindow.setObjectName("editProduct_MainWindow")
        editProduct_MainWindow.resize(640, 720)
        editProduct_MainWindow.setMinimumSize(QtCore.QSize(640, 720))
        editProduct_MainWindow.setMaximumSize(QtCore.QSize(640, 720))
        editProduct_MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.editProduct_centralwidget = QtWidgets.QWidget(parent=editProduct_MainWindow)
        self.editProduct_centralwidget.setObjectName("editProduct_centralwidget")
        self.editProduct_widget_header = QtWidgets.QWidget(parent=self.editProduct_centralwidget)
        self.editProduct_widget_header.setGeometry(QtCore.QRect(0, 0, 640, 88))
        self.editProduct_widget_header.setMinimumSize(QtCore.QSize(640, 88))
        self.editProduct_widget_header.setMaximumSize(QtCore.QSize(640, 88))
        self.editProduct_widget_header.setStyleSheet("QWidget{\n"
"     background-color: rgb(180, 43, 29);\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color:  rgb(255, 255, 255);\n"
"    color: #333;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    font: bold 8pt \"Segoe UI\", \"Arial\";\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e6e6e6;\n"
"    border: 1px solid #bbb;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #dcdcdc;\n"
"    border: 1px solid #aaa;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"    font: 400 20pt \"Segoe UI\", \"Arial\", sans-serif;\n"
"    letter-spacing: 0.5px;\n"
"    padding: 4px 0;\n"
"}")
        self.editProduct_widget_header.setObjectName("editProduct_widget_header")
        self.editProduct_pushButton_back = QtWidgets.QPushButton(parent=self.editProduct_widget_header)
        self.editProduct_pushButton_back.setGeometry(QtCore.QRect(30, 30, 61, 31))
        self.editProduct_pushButton_back.setFlat(False)
        self.editProduct_pushButton_back.setObjectName("editProduct_pushButton_back")
        self.editProduct_label_editProduct = QtWidgets.QLabel(parent=self.editProduct_widget_header)
        self.editProduct_label_editProduct.setGeometry(QtCore.QRect(180, 10, 281, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.editProduct_label_editProduct.setFont(font)
        self.editProduct_label_editProduct.setStyleSheet("")
        self.editProduct_label_editProduct.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.editProduct_label_editProduct.setObjectName("editProduct_label_editProduct")
        self.editProduct_widget_selectOption = QtWidgets.QWidget(parent=self.editProduct_centralwidget)
        self.editProduct_widget_selectOption.setGeometry(QtCore.QRect(70, 260, 501, 231))
        self.editProduct_widget_selectOption.setStyleSheet("QLabel {\n"
"    color: rgb(0, 0, 0);         /* Dark neutral text */\n"
"    font: 12pt \"Segoe UI\", \"Arial\", sans-serif;  /* Clean, modern font */\n"
"    letter-spacing: 0.2px;       /* Subtle spacing for readability */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #F0F0F0;\n"
"    color: #333333;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 4px;\n"
"    padding: 6px 10px;\n"
"    font: 10pt \"Segoe UI\", \"Arial\", sans-serif;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: #F0F0F0;\n"
"    color: #333333;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 4px;\n"
"    text-align: left; padding-left: 10px;\n"
"    font: 12pt \"Segoe UI\", \"Arial\", sans-serif;\n"
"}\n"
"\n"
"/* Optional: highlight on focus */\n"
"QComboBox:focus {\n"
"    border: 1px solid #0078D7;\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.editProduct_widget_selectOption.setObjectName("editProduct_widget_selectOption")
        self.editProduct_label_selectOption = QtWidgets.QLabel(parent=self.editProduct_widget_selectOption)
        self.editProduct_label_selectOption.setGeometry(QtCore.QRect(190, 20, 121, 21))
        self.editProduct_label_selectOption.setMinimumSize(QtCore.QSize(121, 21))
        self.editProduct_label_selectOption.setMaximumSize(QtCore.QSize(121, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.editProduct_label_selectOption.setFont(font)
        self.editProduct_label_selectOption.setStyleSheet("")
        self.editProduct_label_selectOption.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.editProduct_label_selectOption.setObjectName("editProduct_label_selectOption")
        self.editProduct_lineEdit_editValue = QtWidgets.QLineEdit(parent=self.editProduct_widget_selectOption)
        self.editProduct_lineEdit_editValue.setGeometry(QtCore.QRect(80, 170, 341, 40))
        self.editProduct_lineEdit_editValue.setMinimumSize(QtCore.QSize(341, 40))
        self.editProduct_lineEdit_editValue.setMaximumSize(QtCore.QSize(355, 40))
        self.editProduct_lineEdit_editValue.setStyleSheet("")
        self.editProduct_lineEdit_editValue.setText("")
        self.editProduct_lineEdit_editValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.editProduct_lineEdit_editValue.setObjectName("editProduct_lineEdit_editValue")
        self.editProduct_comboBox_options = QtWidgets.QComboBox(parent=self.editProduct_widget_selectOption)
        self.editProduct_comboBox_options.setGeometry(QtCore.QRect(80, 60, 341, 41))
        self.editProduct_comboBox_options.setSizeAdjustPolicy(QtWidgets.QComboBox.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.editProduct_comboBox_options.setObjectName("editProduct_comboBox_options")
        self.editProduct_comboBox_options.addItem("")
        self.editProduct_comboBox_options.addItem("")
        self.editProduct_comboBox_options.addItem("")
        self.editProduct_pushButton_confirm = QtWidgets.QPushButton(parent=self.editProduct_centralwidget)
        self.editProduct_pushButton_confirm.setGeometry(QtCore.QRect(210, 540, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.editProduct_pushButton_confirm.setFont(font)
        self.editProduct_pushButton_confirm.setStyleSheet("QPushButton {\n"
"    background-color: #B42B1D;         /* Flat red */\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 6px;                /* Optional: remove if you want sharp corners */\n"
"    font: bold 12pt \"Segoe UI\", \"Arial\", sans-serif;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #a1281a;         /* Slightly darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #8c2116;         /* Even darker when pressed */\n"
"}")
        self.editProduct_pushButton_confirm.setObjectName("editProduct_pushButton_confirm")
        self.editProduct_label_productName = QtWidgets.QLabel(parent=self.editProduct_centralwidget)
        self.editProduct_label_productName.setGeometry(QtCore.QRect(70, 150, 501, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.editProduct_label_productName.setFont(font)
        self.editProduct_label_productName.setStyleSheet("QLabel {\n"
"    rgb(0, 0, 0)            /* Dark neutral text */\n"
"    font: bold 20pt \"Segoe UI\", \"Arial\", sans-serif;  /* Clean, modern font */\n"
"    letter-spacing: 0.2px;       /* Subtle spacing for readability */\n"
"}")
        self.editProduct_label_productName.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.editProduct_label_productName.setObjectName("editProduct_label_productName")
        self.editProduct_label_stock = QtWidgets.QLabel(parent=self.editProduct_centralwidget)
        self.editProduct_label_stock.setGeometry(QtCore.QRect(220, 200, 201, 20))
        self.editProduct_label_stock.setStyleSheet("QLabel {\n"
"    color: #333333;  \n"
"    font: 12pt \"Segoe UI\", \"Arial\", sans-serif;  /* Clean, modern font */\n"
"    letter-spacing: 0.2px;       /* Subtle spacing for readability */\n"
"}\n"
"")
        self.editProduct_label_stock.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.editProduct_label_stock.setObjectName("editProduct_label_stock")
        self.editProduct_label_Error = QtWidgets.QLabel(parent=self.editProduct_centralwidget)
        self.editProduct_label_Error.setGeometry(QtCore.QRect(210, 620, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.editProduct_label_Error.setFont(font)
        self.editProduct_label_Error.setStyleSheet("QLabel {\n"
"    color: rgb(180, 43, 29);\n"
"    font: 10pt \"Segoe UI\", \"Arial\", sans-serif;  /* Clean, modern font */\n"
"    letter-spacing: 0.2px;       /* Subtle spacing for readability */\n"
"}")
        self.editProduct_label_Error.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.editProduct_label_Error.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.editProduct_label_Error.setObjectName("editProduct_label_Error")
        editProduct_MainWindow.setCentralWidget(self.editProduct_centralwidget)

        self.retranslateUi(editProduct_MainWindow)
        self.editProduct_comboBox_options.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(editProduct_MainWindow)

    def retranslateUi(self, editProduct_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        editProduct_MainWindow.setWindowTitle(_translate("editProduct_MainWindow", "Ngyopify : Edit Product"))
        self.editProduct_pushButton_back.setText(_translate("editProduct_MainWindow", "Back"))
        self.editProduct_label_editProduct.setText(_translate("editProduct_MainWindow", "Edit Product"))
        self.editProduct_label_editProduct.setProperty("aaaa", _translate("editProduct_MainWindow", "sa"))
        self.editProduct_label_selectOption.setText(_translate("editProduct_MainWindow", "Select Option"))
        self.editProduct_label_selectOption.setProperty("aaaa", _translate("editProduct_MainWindow", "sa"))
        self.editProduct_lineEdit_editValue.setPlaceholderText(_translate("editProduct_MainWindow", "Edit Value"))
        self.editProduct_comboBox_options.setCurrentText(_translate("editProduct_MainWindow", "Remove Product"))
        self.editProduct_comboBox_options.setItemText(0, _translate("editProduct_MainWindow", "Remove Product"))
        self.editProduct_comboBox_options.setItemText(1, _translate("editProduct_MainWindow", "Edit Stock"))
        self.editProduct_comboBox_options.setItemText(2, _translate("editProduct_MainWindow", "Edit Price"))
        self.editProduct_pushButton_confirm.setText(_translate("editProduct_MainWindow", "Confirm"))
        self.editProduct_label_productName.setText(_translate("editProduct_MainWindow", "Product Name"))
        self.editProduct_label_productName.setProperty("aaaa", _translate("editProduct_MainWindow", "sa"))
        self.editProduct_label_stock.setText(_translate("editProduct_MainWindow", "Product Stock: ###"))
        self.editProduct_label_Error.setText(_translate("editProduct_MainWindow", ""))
        self.editProduct_label_Error.setProperty("aaaa", _translate("editProduct_MainWindow", "sa"))
