# Form implementation generated from reading ui file 'ProductDetails_UI.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_productDetails_MainWindow(object):
    def setupUi(self, productDetails_MainWindow):
        productDetails_MainWindow.setObjectName("productDetails_MainWindow")
        productDetails_MainWindow.resize(1280, 720)
        productDetails_MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        productDetails_MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        self.productDetails_centralwidget = QtWidgets.QWidget(parent=productDetails_MainWindow)
        self.productDetails_centralwidget.setObjectName("productDetails_centralwidget")
        self.productDetails_widget_header = QtWidgets.QWidget(parent=self.productDetails_centralwidget)
        self.productDetails_widget_header.setGeometry(QtCore.QRect(0, 0, 1280, 88))
        self.productDetails_widget_header.setMinimumSize(QtCore.QSize(1280, 88))
        self.productDetails_widget_header.setMaximumSize(QtCore.QSize(1280, 88))
        self.productDetails_widget_header.setStyleSheet("QWidget{\n"
"     background-color: rgb(180, 43, 29);\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color:  rgb(255, 255, 255);\n"
"    color: #333;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    font: bold 8pt \"Segoe UI\", \"Arial\";\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e6e6e6;\n"
"    border: 1px solid #bbb;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #dcdcdc;\n"
"    border: 1px solid #aaa;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"    font: 400 20pt \"Segoe UI\", \"Arial\", sans-serif;\n"
"    letter-spacing: 0.5px;\n"
"    padding: 4px 0;\n"
"}")
        self.productDetails_widget_header.setObjectName("productDetails_widget_header")
        self.productDetails_label_productDetails = QtWidgets.QLabel(parent=self.productDetails_widget_header)
        self.productDetails_label_productDetails.setGeometry(QtCore.QRect(440, 10, 401, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.productDetails_label_productDetails.setFont(font)
        self.productDetails_label_productDetails.setStyleSheet("")
        self.productDetails_label_productDetails.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.productDetails_label_productDetails.setObjectName("productDetails_label_productDetails")
        self.productDetails_pushButton_back = QtWidgets.QPushButton(parent=self.productDetails_widget_header)
        self.productDetails_pushButton_back.setGeometry(QtCore.QRect(40, 30, 81, 31))
        self.productDetails_pushButton_back.setFlat(False)
        self.productDetails_pushButton_back.setObjectName("productDetails_pushButton_back")
        self.productDetails_widget_main = QtWidgets.QWidget(parent=self.productDetails_centralwidget)
        self.productDetails_widget_main.setGeometry(QtCore.QRect(130, 130, 1020, 530))
        self.productDetails_widget_main.setMinimumSize(QtCore.QSize(1020, 530))
        self.productDetails_widget_main.setMaximumSize(QtCore.QSize(1020, 530))
        self.productDetails_widget_main.setStyleSheet("QWidget #product_details_widget {\n"
"    border-radius: 10px;  /* optional, remove if you want sharp corners */\n"
"    background-color: rgb(217, 217, 217,128);\n"
"}")
        self.productDetails_widget_main.setObjectName("productDetails_widget_main")
        self.productDetails_widget_productImage = QtWidgets.QWidget(parent=self.productDetails_widget_main)
        self.productDetails_widget_productImage.setGeometry(QtCore.QRect(80, 60, 300, 400))
        self.productDetails_widget_productImage.setMinimumSize(QtCore.QSize(300, 400))
        self.productDetails_widget_productImage.setMaximumSize(QtCore.QSize(300, 400))
        self.productDetails_widget_productImage.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.productDetails_widget_productImage.setObjectName("productDetails_widget_productImage")
        self.productDetails_label_productImage = QtWidgets.QLabel(parent=self.productDetails_widget_productImage)
        self.productDetails_label_productImage.setGeometry(QtCore.QRect(0, 0, 301, 401))
        self.productDetails_label_productImage.setText("")
        self.productDetails_label_productImage.setScaledContents(True)
        self.productDetails_label_productImage.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.productDetails_label_productImage.setObjectName("productDetails_label_productImage")
        self.productDetails_label_productName = QtWidgets.QLabel(parent=self.productDetails_widget_main)
        self.productDetails_label_productName.setGeometry(QtCore.QRect(430, 60, 521, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.productDetails_label_productName.setFont(font)
        self.productDetails_label_productName.setStyleSheet("QLabel {\n"
"    rgb(0, 0, 0)            /* Dark neutral text */\n"
"    font: bold 20pt \"Segoe UI\", \"Arial\", sans-serif;  /* Clean, modern font */\n"
"    letter-spacing: 0.2px;       /* Subtle spacing for readability */\n"
"}")
        self.productDetails_label_productName.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.productDetails_label_productName.setObjectName("productDetails_label_productName")
        self.productDetails_label_price = QtWidgets.QLabel(parent=self.productDetails_widget_main)
        self.productDetails_label_price.setGeometry(QtCore.QRect(430, 130, 521, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.productDetails_label_price.setFont(font)
        self.productDetails_label_price.setStyleSheet("QLabel {\n"
"    color: rgb(180, 43, 29);         /* Dark neutral text */\n"
"    font: 20pt \"Segoe UI\", \"Arial\", sans-serif;  /* Clean, modern font */\n"
"    letter-spacing: 0.2px;       /* Subtle spacing for readability */\n"
"}")
        self.productDetails_label_price.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.productDetails_label_price.setObjectName("productDetails_label_price")
        self.productDetails_label_categoryLabel = QtWidgets.QLabel(parent=self.productDetails_widget_main)
        self.productDetails_label_categoryLabel.setGeometry(QtCore.QRect(430, 200, 521, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.productDetails_label_categoryLabel.setFont(font)
        self.productDetails_label_categoryLabel.setStyleSheet("QLabel {\n"
"     color: #333333;          /* Dark neutral text */\n"
"    font: 12pt \"Segoe UI\", \"Arial\", sans-serif;  /* Clean, modern font */\n"
"    letter-spacing: 0.2px;       /* Subtle spacing for readability */\n"
"}")
        self.productDetails_label_categoryLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.productDetails_label_categoryLabel.setObjectName("productDetails_label_categoryLabel")
        self.productDetails_label_categoryName = QtWidgets.QLabel(parent=self.productDetails_widget_main)
        self.productDetails_label_categoryName.setGeometry(QtCore.QRect(430, 230, 521, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.productDetails_label_categoryName.setFont(font)
        self.productDetails_label_categoryName.setStyleSheet("QLabel {\n"
"    color: rgb(0, 0, 0);         /* Dark neutral text */\n"
"    font: 16pt \"Segoe UI\", \"Arial\", sans-serif;  /* Clean, modern font */\n"
"    letter-spacing: 0.2px;       /* Subtle spacing for readability */\n"
"}")
        self.productDetails_label_categoryName.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.productDetails_label_categoryName.setObjectName("productDetails_label_categoryName")
        self.productDetails_label_sellerLabel = QtWidgets.QLabel(parent=self.productDetails_widget_main)
        self.productDetails_label_sellerLabel.setGeometry(QtCore.QRect(430, 290, 521, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.productDetails_label_sellerLabel.setFont(font)
        self.productDetails_label_sellerLabel.setStyleSheet("QLabel {\n"
"     color: #333333;          /* Dark neutral text */\n"
"    font: 12pt \"Segoe UI\", \"Arial\", sans-serif;  /* Clean, modern font */\n"
"    letter-spacing: 0.2px;       /* Subtle spacing for readability */\n"
"}")
        self.productDetails_label_sellerLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.productDetails_label_sellerLabel.setObjectName("productDetails_label_sellerLabel")
        self.productDetails_label_sellerName = QtWidgets.QLabel(parent=self.productDetails_widget_main)
        self.productDetails_label_sellerName.setGeometry(QtCore.QRect(430, 320, 521, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.productDetails_label_sellerName.setFont(font)
        self.productDetails_label_sellerName.setStyleSheet("QLabel {\n"
"    color: rgb(0, 0, 0);         /* Dark neutral text */\n"
"    font: 16pt \"Segoe UI\", \"Arial\", sans-serif;  /* Clean, modern font */\n"
"    letter-spacing: 0.2px;       /* Subtle spacing for readability */\n"
"}")
        self.productDetails_label_sellerName.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.productDetails_label_sellerName.setObjectName("productDetails_label_sellerName")
        self.productDetails_label_quantity = QtWidgets.QLabel(parent=self.productDetails_widget_main)
        self.productDetails_label_quantity.setGeometry(QtCore.QRect(430, 380, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.productDetails_label_quantity.setFont(font)
        self.productDetails_label_quantity.setStyleSheet("QLabel {\n"
"     color: #333333;          /* Dark neutral text */\n"
"    font: 12pt \"Segoe UI\", \"Arial\", sans-serif;  /* Clean, modern font */\n"
"    letter-spacing: 0.2px;       /* Subtle spacing for readability */\n"
"}")
        self.productDetails_label_quantity.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.productDetails_label_quantity.setObjectName("productDetails_label_quantity")
        self.productDetails_pushButton_addCart = QtWidgets.QPushButton(parent=self.productDetails_widget_main)
        self.productDetails_pushButton_addCart.setGeometry(QtCore.QRect(430, 430, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.productDetails_pushButton_addCart.setFont(font)
        self.productDetails_pushButton_addCart.setStyleSheet("QPushButton {\n"
"    background-color: #B42B1D;         /* Flat red */\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 6px;                /* Optional: remove if you want sharp corners */\n"
"    font: bold 9pt \"Segoe UI\", \"Arial\", sans-serif;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #a1281a;         /* Slightly darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #8c2116;         /* Even darker when pressed */\n"
"}")
        self.productDetails_pushButton_addCart.setObjectName("productDetails_pushButton_addCart")
        self.productDetails_spinBox_quantity = QtWidgets.QSpinBox(parent=self.productDetails_widget_main)
        self.productDetails_spinBox_quantity.setGeometry(QtCore.QRect(510, 381, 71, 21))
        self.productDetails_spinBox_quantity.setStyleSheet("QSpinBox {\n"
"    color: #333333;\n"
"    font: 9pt \"Segoe UI\", \"Arial\", sans-serif;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 4px;\n"
"    padding: 2px 6px;\n"
"}\n"
"")
        self.productDetails_spinBox_quantity.setMinimum(1)
        self.productDetails_spinBox_quantity.setMaximum(99)
        self.productDetails_spinBox_quantity.setObjectName("productDetails_spinBox_quantity")
        self.productDetails_label_stock = QtWidgets.QLabel(parent=self.productDetails_widget_main)
        self.productDetails_label_stock.setGeometry(QtCore.QRect(600, 380, 341, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.productDetails_label_stock.setFont(font)
        self.productDetails_label_stock.setStyleSheet("QLabel {\n"
"     color: #333333;          /* Dark neutral text */\n"
"    font: 12pt \"Segoe UI\", \"Arial\", sans-serif;  /* Clean, modern font */\n"
"    letter-spacing: 0.2px;       /* Subtle spacing for readability */\n"
"}")
        self.productDetails_label_stock.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.productDetails_label_stock.setObjectName("productDetails_label_stock")
        self.productDetails_label_Error = QtWidgets.QLabel(parent=self.productDetails_widget_main)
        self.productDetails_label_Error.setGeometry(QtCore.QRect(760, 430, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.productDetails_label_Error.setFont(font)
        self.productDetails_label_Error.setStyleSheet("QLabel {\n"
"    color: rgb(180, 43, 29);\n"
"    font: 12pt \"Segoe UI\", \"Arial\", sans-serif;  /* Clean, modern font */\n"
"    letter-spacing: 0.2px;       /* Subtle spacing for readability */\n"
"}")
        self.productDetails_label_Error.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.productDetails_label_Error.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.productDetails_label_Error.setObjectName("productDetails_label_Error")
        productDetails_MainWindow.setCentralWidget(self.productDetails_centralwidget)

        self.retranslateUi(productDetails_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(productDetails_MainWindow)

    def retranslateUi(self, productDetails_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        productDetails_MainWindow.setWindowTitle(_translate("productDetails_MainWindow", "Ngyopify : Product Details"))
        self.productDetails_label_productDetails.setText(_translate("productDetails_MainWindow", "Product Details"))
        self.productDetails_label_productDetails.setProperty("aaaa", _translate("productDetails_MainWindow", "sa"))
        self.productDetails_pushButton_back.setText(_translate("productDetails_MainWindow", "Back"))
        self.productDetails_label_productName.setText(_translate("productDetails_MainWindow", "Product Name"))
        self.productDetails_label_productName.setProperty("aaaa", _translate("productDetails_MainWindow", "sa"))
        self.productDetails_label_price.setText(_translate("productDetails_MainWindow", "₱ 000,000.00"))
        self.productDetails_label_price.setProperty("aaaa", _translate("productDetails_MainWindow", "sa"))
        self.productDetails_label_categoryLabel.setText(_translate("productDetails_MainWindow", "Category"))
        self.productDetails_label_categoryLabel.setProperty("aaaa", _translate("productDetails_MainWindow", "sa"))
        self.productDetails_label_categoryName.setText(_translate("productDetails_MainWindow", "Category Name"))
        self.productDetails_label_categoryName.setProperty("aaaa", _translate("productDetails_MainWindow", "sa"))
        self.productDetails_label_sellerLabel.setText(_translate("productDetails_MainWindow", "Seller"))
        self.productDetails_label_sellerLabel.setProperty("aaaa", _translate("productDetails_MainWindow", "sa"))
        self.productDetails_label_sellerName.setText(_translate("productDetails_MainWindow", "Seller Name"))
        self.productDetails_label_sellerName.setProperty("aaaa", _translate("productDetails_MainWindow", "sa"))
        self.productDetails_label_quantity.setText(_translate("productDetails_MainWindow", "Quantity"))
        self.productDetails_label_quantity.setProperty("aaaa", _translate("productDetails_MainWindow", "sa"))
        self.productDetails_pushButton_addCart.setText(_translate("productDetails_MainWindow", "Add to Cart"))
        self.productDetails_label_stock.setText(_translate("productDetails_MainWindow", "##  pieces available"))
        self.productDetails_label_stock.setProperty("aaaa", _translate("productDetails_MainWindow", "sa"))
        self.productDetails_label_Error.setText(_translate("productDetails_MainWindow", ""))
        self.productDetails_label_Error.setProperty("aaaa", _translate("productDetails_MainWindow", "sa"))
