# Form implementation generated from reading ui file 'Purchases_UI.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_myPurchases_MainWindow(object):
    def setupUi(self, myPurchases_MainWindow):
        myPurchases_MainWindow.setObjectName("myPurchases_MainWindow")
        myPurchases_MainWindow.resize(640, 720)
        myPurchases_MainWindow.setMinimumSize(QtCore.QSize(640, 720))
        myPurchases_MainWindow.setMaximumSize(QtCore.QSize(640, 720))
        myPurchases_MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.myPurchases_centralwidget = QtWidgets.QWidget(parent=myPurchases_MainWindow)
        self.myPurchases_centralwidget.setObjectName("myPurchases_centralwidget")
        self.myPurchases_widget_header = QtWidgets.QWidget(parent=self.myPurchases_centralwidget)
        self.myPurchases_widget_header.setGeometry(QtCore.QRect(0, 0, 640, 88))
        self.myPurchases_widget_header.setMinimumSize(QtCore.QSize(640, 88))
        self.myPurchases_widget_header.setMaximumSize(QtCore.QSize(640, 88))
        self.myPurchases_widget_header.setStyleSheet("QWidget{\n"
"     background-color: rgb(180, 43, 29);\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color:  rgb(255, 255, 255);\n"
"    color: #333;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    font: bold 8pt \"Segoe UI\", \"Arial\";\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e6e6e6;\n"
"    border: 1px solid #bbb;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #dcdcdc;\n"
"    border: 1px solid #aaa;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"    font: 400 20pt \"Segoe UI\", \"Arial\", sans-serif;\n"
"    letter-spacing: 0.5px;\n"
"    padding: 4px 0;\n"
"}")
        self.myPurchases_widget_header.setObjectName("myPurchases_widget_header")
        self.myPurchases_pushButton_back = QtWidgets.QPushButton(parent=self.myPurchases_widget_header)
        self.myPurchases_pushButton_back.setGeometry(QtCore.QRect(30, 30, 61, 31))
        self.myPurchases_pushButton_back.setFlat(False)
        self.myPurchases_pushButton_back.setObjectName("myPurchases_pushButton_back")
        self.myPurchases_label_myPurchases = QtWidgets.QLabel(parent=self.myPurchases_widget_header)
        self.myPurchases_label_myPurchases.setGeometry(QtCore.QRect(180, 10, 281, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.myPurchases_label_myPurchases.setFont(font)
        self.myPurchases_label_myPurchases.setStyleSheet("")
        self.myPurchases_label_myPurchases.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.myPurchases_label_myPurchases.setObjectName("myPurchases_label_myPurchases")
        self.myPurchases_tableWidget_transactionHistory = QtWidgets.QTableWidget(parent=self.myPurchases_centralwidget)
        self.myPurchases_tableWidget_transactionHistory.setGeometry(QtCore.QRect(70, 161, 501, 471))
        self.myPurchases_tableWidget_transactionHistory.setStyleSheet("QTableWidget {\n"
"    background-color: #F9F9F9;\n"
"    color: #333333;\n"
"    border: 1px solid #CCCCCC;\n"
"    gridline-color: #E0E0E0;\n"
"    font: 9pt \"Segoe UI\", \"Arial\", sans-serif;\n"
"    selection-background-color: #0078D7;\n"
"    selection-color: white;\n"
"    outline: 0;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #E6E6E6;\n"
"    color: #333;\n"
"    font-weight: 600;\n"
"    padding: 6px;\n"
"    border: 1px solid #CCCCCC;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 6px;\n"
"    border: none;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #0078D7;\n"
"    color: white;\n"
"}\n"
"")
        self.myPurchases_tableWidget_transactionHistory.setObjectName("myPurchases_tableWidget_transactionHistory")
        self.myPurchases_tableWidget_transactionHistory.setColumnCount(0)
        self.myPurchases_tableWidget_transactionHistory.setRowCount(0)
        myPurchases_MainWindow.setCentralWidget(self.myPurchases_centralwidget)

        self.retranslateUi(myPurchases_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(myPurchases_MainWindow)

    def retranslateUi(self, myPurchases_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        myPurchases_MainWindow.setWindowTitle(_translate("myPurchases_MainWindow", "Ngyopify : My Purchases"))
        self.myPurchases_pushButton_back.setText(_translate("myPurchases_MainWindow", "Back"))
        self.myPurchases_label_myPurchases.setText(_translate("myPurchases_MainWindow", "My Purchases"))
        self.myPurchases_label_myPurchases.setProperty("aaaa", _translate("myPurchases_MainWindow", "sa"))
