# Form implementation generated from reading ui file 'Seller_UI.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QSizePolicy


class Ui_seller_MainWindow(object):
    def setupUi(self, seller_MainWindow):
        seller_MainWindow.setObjectName("seller_MainWindow")
        seller_MainWindow.resize(1280, 720)
        seller_MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        seller_MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        seller_MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.seller_centralwidget = QtWidgets.QWidget(parent=seller_MainWindow)
        self.seller_centralwidget.setObjectName("seller_centralwidget")
        self.selelr_widget_header = QtWidgets.QWidget(parent=self.seller_centralwidget)
        self.selelr_widget_header.setGeometry(QtCore.QRect(0, 0, 1280, 88))
        self.selelr_widget_header.setMinimumSize(QtCore.QSize(1280, 88))
        self.selelr_widget_header.setMaximumSize(QtCore.QSize(1280, 88))
        self.selelr_widget_header.setStyleSheet("QWidget{\n"
"     background-color: rgb(180, 43, 29);\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color:  rgb(255, 255, 255);\n"
"    color: #333;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    font: bold 8pt \"Segoe UI\", \"Arial\";\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e6e6e6;\n"
"    border: 1px solid #bbb;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #dcdcdc;\n"
"    border: 1px solid #aaa;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"    font: 600 20pt \"Segoe UI\", \"Arial\", sans-serif;\n"
"    letter-spacing: 0.5px;\n"
"    padding: 4px 0;\n"
"}")
        self.selelr_widget_header.setObjectName("selelr_widget_header")
        self.seller_label_sellerCentre = QtWidgets.QLabel(parent=self.selelr_widget_header)
        self.seller_label_sellerCentre.setGeometry(QtCore.QRect(490, 10, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.seller_label_sellerCentre.setFont(font)
        self.seller_label_sellerCentre.setStyleSheet("")
        self.seller_label_sellerCentre.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.seller_label_sellerCentre.setObjectName("seller_label_sellerCentre")
        self.seller_pushButton_logOut = QtWidgets.QPushButton(parent=self.selelr_widget_header)
        self.seller_pushButton_logOut.setGeometry(QtCore.QRect(1160, 30, 81, 31))
        self.seller_pushButton_logOut.setFlat(False)
        self.seller_pushButton_logOut.setObjectName("seller_pushButton_logOut")
        self.seller_label_myProducts = QtWidgets.QLabel(parent=self.seller_centralwidget)
        self.seller_label_myProducts.setGeometry(QtCore.QRect(80, 120, 531, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.seller_label_myProducts.setFont(font)
        self.seller_label_myProducts.setStyleSheet("QLabel {\n"
"    color: #333333;              /* Dark neutral text */\n"
"    font: bold 20pt \"Segoe UI\", \"Arial\", sans-serif;  /* Clean, modern font */\n"
"    letter-spacing: 0.2px;       /* Subtle spacing for readability */\n"
"}")
        self.seller_label_myProducts.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.seller_label_myProducts.setObjectName("seller_label_myProducts")
        self.seller_widget_myProducts = QtWidgets.QWidget(parent=self.seller_centralwidget)
        self.seller_widget_myProducts.setGeometry(QtCore.QRect(80, 180, 531, 481))
        self.seller_widget_myProducts.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.seller_widget_myProducts.setObjectName("seller_widget_myProducts")
        self.seller_scrollArea_myProducts = QtWidgets.QScrollArea(parent=self.seller_widget_myProducts)
        self.seller_scrollArea_myProducts.setGeometry(QtCore.QRect(0, 0, 531, 481))
        self.seller_scrollArea_myProducts.setWidgetResizable(True)
        self.seller_scrollArea_myProducts.setObjectName("seller_scrollArea_myProducts")
        self.seller_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.seller_scrollAreaWidgetContents.setSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        self.seller_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 529, 479))
        self.seller_scrollAreaWidgetContents.setObjectName("seller_scrollAreaWidgetContents")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.seller_scrollAreaWidgetContents)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 531, 481))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.seller_gridLayout_myProducts = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.seller_gridLayout_myProducts.setContentsMargins(0, 0, 0, 0)
        self.seller_gridLayout_myProducts.setObjectName("seller_gridLayout_myProducts")
        self.seller_scrollArea_myProducts.setWidget(self.seller_scrollAreaWidgetContents)
        self.seller_widget_productOrders = QtWidgets.QWidget(parent=self.seller_centralwidget)
        self.seller_widget_productOrders.setGeometry(QtCore.QRect(690, 140, 501, 61))
        self.seller_widget_productOrders.setStyleSheet("QWidget{ background-color: rgb(180, 43, 29); }\n"
"\n"
"QLabel {\n"
"    \n"
"    color: rgb(255,255,255);\n"
"    font: 16pt  \"Segoe UI\", \"Arial\", sans-serif;  /* Clean, modern font */\n"
"}")
        self.seller_widget_productOrders.setObjectName("seller_widget_productOrders")
        self.seller_label_productOrder = QtWidgets.QLabel(parent=self.seller_widget_productOrders)
        self.seller_label_productOrder.setGeometry(QtCore.QRect(20, 0, 461, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.seller_label_productOrder.setFont(font)
        self.seller_label_productOrder.setStyleSheet("")
        self.seller_label_productOrder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.seller_label_productOrder.setObjectName("seller_label_productOrder")
        self.seller_tableWidget_productOrders = QtWidgets.QTableWidget(parent=self.seller_centralwidget)
        self.seller_tableWidget_productOrders.setGeometry(QtCore.QRect(690, 201, 501, 411))
        self.seller_tableWidget_productOrders.setStyleSheet("QTableWidget {\n"
"    background-color: #F9F9F9;\n"
"    color: #333333;\n"
"    border: 1px solid #CCCCCC;\n"
"    gridline-color: #E0E0E0;\n"
"    font: 9pt \"Segoe UI\", \"Arial\", sans-serif;\n"
"    selection-background-color: #0078D7;\n"
"    selection-color: white;\n"
"    outline: 0;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #E6E6E6;\n"
"    color: #333;\n"
"    font-weight: 600;\n"
"    padding: 6px;\n"
"    border: 1px solid #CCCCCC;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 6px;\n"
"    border: none;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #0078D7;\n"
"    color: white;\n"
"}\n"
"")
        self.seller_tableWidget_productOrders.setObjectName("seller_tableWidget_productOrders")
        self.seller_tableWidget_productOrders.setColumnCount(0)
        self.seller_tableWidget_productOrders.setRowCount(0)
        self.seller_pushButton_addProduct = QtWidgets.QPushButton(parent=self.seller_centralwidget)
        self.seller_pushButton_addProduct.setGeometry(QtCore.QRect(690, 630, 501, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.seller_pushButton_addProduct.setFont(font)
        self.seller_pushButton_addProduct.setStyleSheet("QPushButton {\n"
"    background-color: #B42B1D;         /* Flat red */\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 6px;                /* Optional: remove if you want sharp corners */\n"
"    font: bold 9pt \"Segoe UI\", \"Arial\", sans-serif;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #a1281a;         /* Slightly darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #8c2116;         /* Even darker when pressed */\n"
"}")
        self.seller_pushButton_addProduct.setObjectName("seller_pushButton_addProduct")
        seller_MainWindow.setCentralWidget(self.seller_centralwidget)

        self.retranslateUi(seller_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(seller_MainWindow)

    def retranslateUi(self, seller_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        seller_MainWindow.setWindowTitle(_translate("seller_MainWindow", "Ngyopify : Seller Centre"))
        self.seller_label_sellerCentre.setText(_translate("seller_MainWindow", "Ngyopify Seller Centre"))
        self.seller_label_sellerCentre.setProperty("aaaa", _translate("seller_MainWindow", "sa"))
        self.seller_pushButton_logOut.setText(_translate("seller_MainWindow", "Log Out"))
        self.seller_label_myProducts.setText(_translate("seller_MainWindow", "My Products"))
        self.seller_label_myProducts.setProperty("aaaa", _translate("seller_MainWindow", "sa"))
        self.seller_label_productOrder.setText(_translate("seller_MainWindow", "Product Orders"))
        self.seller_label_productOrder.setProperty("aaaa", _translate("seller_MainWindow", "sa"))
        self.seller_pushButton_addProduct.setText(_translate("seller_MainWindow", "Add Product"))
