# Form implementation generated from reading ui file 'ShoppingCart_UI.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_shoppingCart_MainWindow(object):
    def setupUi(self, shoppingCart_MainWindow):
        shoppingCart_MainWindow.setObjectName("shoppingCart_MainWindow")
        shoppingCart_MainWindow.resize(1280, 720)
        shoppingCart_MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        shoppingCart_MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        shoppingCart_MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.shoppingCart_centralwidget = QtWidgets.QWidget(parent=shoppingCart_MainWindow)
        self.shoppingCart_centralwidget.setObjectName("shoppingCart_centralwidget")
        self.shoppingCart_widget_header = QtWidgets.QWidget(parent=self.shoppingCart_centralwidget)
        self.shoppingCart_widget_header.setGeometry(QtCore.QRect(0, 0, 1280, 88))
        self.shoppingCart_widget_header.setMinimumSize(QtCore.QSize(1280, 88))
        self.shoppingCart_widget_header.setMaximumSize(QtCore.QSize(1280, 88))
        self.shoppingCart_widget_header.setStyleSheet("QWidget{\n"
"     background-color: rgb(180, 43, 29);\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color:  rgb(255, 255, 255);\n"
"    color: #333;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    font: bold 8pt \"Segoe UI\", \"Arial\";\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e6e6e6;\n"
"    border: 1px solid #bbb;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #dcdcdc;\n"
"    border: 1px solid #aaa;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"    font: 400 20pt \"Segoe UI\", \"Arial\", sans-serif;\n"
"    letter-spacing: 0.5px;\n"
"    padding: 4px 0;\n"
"}")
        self.shoppingCart_widget_header.setObjectName("shoppingCart_widget_header")
        self.shoppingCart_label_shoppingCart = QtWidgets.QLabel(parent=self.shoppingCart_widget_header)
        self.shoppingCart_label_shoppingCart.setGeometry(QtCore.QRect(440, 10, 401, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.shoppingCart_label_shoppingCart.setFont(font)
        self.shoppingCart_label_shoppingCart.setStyleSheet("")
        self.shoppingCart_label_shoppingCart.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.shoppingCart_label_shoppingCart.setObjectName("shoppingCart_label_shoppingCart")
        self.shoppingCart_pushButton_back = QtWidgets.QPushButton(parent=self.shoppingCart_widget_header)
        self.shoppingCart_pushButton_back.setGeometry(QtCore.QRect(40, 30, 81, 31))
        self.shoppingCart_pushButton_back.setFlat(False)
        self.shoppingCart_pushButton_back.setObjectName("shoppingCart_pushButton_back")
        self.shoppingCart_tableWidget_shoppingCart = QtWidgets.QTableWidget(parent=self.shoppingCart_centralwidget)
        self.shoppingCart_tableWidget_shoppingCart.setGeometry(QtCore.QRect(190, 150, 901, 441))
        self.shoppingCart_tableWidget_shoppingCart.setStyleSheet("QTableWidget {\n"
"    background-color: #F9F9F9;\n"
"    color: #333333;\n"
"    border: 1px solid #CCCCCC;\n"
"    gridline-color: #E0E0E0;\n"
"    font: 9pt \"Segoe UI\", \"Arial\", sans-serif;\n"
"    selection-background-color: #0078D7;\n"
"    selection-color: white;\n"
"    outline: 0;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #E6E6E6;\n"
"    color: #333;\n"
"    font-weight: 600;\n"
"    padding: 6px;\n"
"    border: 1px solid #CCCCCC;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 6px;\n"
"    border: none;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #0078D7;\n"
"    color: white;\n"
"}\n"
"")
        self.shoppingCart_tableWidget_shoppingCart.setAlternatingRowColors(True)
        self.shoppingCart_tableWidget_shoppingCart.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.shoppingCart_tableWidget_shoppingCart.setShowGrid(True)
        self.shoppingCart_tableWidget_shoppingCart.setObjectName("shoppingCart_tableWidget_shoppingCart")
        self.shoppingCart_tableWidget_shoppingCart.setColumnCount(0)
        self.shoppingCart_tableWidget_shoppingCart.setRowCount(0)
        self.shoppingCart_tableWidget_shoppingCart.horizontalHeader().setCascadingSectionResizes(False)
        self.shoppingCart_tableWidget_shoppingCart.horizontalHeader().setMinimumSectionSize(39)
        self.shoppingCart_tableWidget_shoppingCart.horizontalHeader().setSortIndicatorShown(False)
        self.shoppingCart_tableWidget_shoppingCart.horizontalHeader().setStretchLastSection(False)
        self.shoppingCart_tableWidget_shoppingCart.verticalHeader().setStretchLastSection(False)
        self.shoppingCart_pushButton_removeItem = QtWidgets.QPushButton(parent=self.shoppingCart_centralwidget)
        self.shoppingCart_pushButton_removeItem.setGeometry(QtCore.QRect(190, 620, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.shoppingCart_pushButton_removeItem.setFont(font)
        self.shoppingCart_pushButton_removeItem.setStyleSheet("QPushButton {\n"
"    background-color: #D9D9D9;         /* Light neutral gray */\n"
"    color: #333333;                    /* Dark text for contrast */\n"
"    border: none;\n"
"    border-radius: 6px;                /* You can change to 0px for square corners */\n"
"    font: 9pt \"Segoe UI\", \"Arial\", sans-serif;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #CFCFCF;         /* Slightly darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #BFBFBF;         /* Darker when pressed */\n"
"}\n"
"")
        self.shoppingCart_pushButton_removeItem.setObjectName("shoppingCart_pushButton_removeItem")
        self.shoppingCart_pushButton_placeOrder = QtWidgets.QPushButton(parent=self.shoppingCart_centralwidget)
        self.shoppingCart_pushButton_placeOrder.setGeometry(QtCore.QRect(920, 620, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.shoppingCart_pushButton_placeOrder.setFont(font)
        self.shoppingCart_pushButton_placeOrder.setStyleSheet("QPushButton {\n"
"    background-color: #B42B1D;         /* Flat red */\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 6px;                /* Optional: remove if you want sharp corners */\n"
"    font: bold 9pt \"Segoe UI\", \"Arial\", sans-serif;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #a1281a;         /* Slightly darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #8c2116;         /* Even darker when pressed */\n"
"}")
        self.shoppingCart_pushButton_placeOrder.setObjectName("shoppingCart_pushButton_placeOrder")
        self.shoppingCart_label_totalAmount = QtWidgets.QLabel(parent=self.shoppingCart_centralwidget)
        self.shoppingCart_label_totalAmount.setGeometry(QtCore.QRect(670, 620, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.shoppingCart_label_totalAmount.setFont(font)
        self.shoppingCart_label_totalAmount.setStyleSheet("QLabel {\n"
"    color: rgb(180, 43, 29);         /* Dark neutral text */\n"
"    font: bold 12pt \"Segoe UI\", \"Arial\", sans-serif;  /* Clean, modern font */\n"
"    letter-spacing: 0.2px;       /* Subtle spacing for readability */\n"
"}")
        self.shoppingCart_label_totalAmount.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.shoppingCart_label_totalAmount.setObjectName("shoppingCart_label_totalAmount")
        self.shoppingCart_label_Error = QtWidgets.QLabel(parent=self.shoppingCart_centralwidget)
        self.shoppingCart_label_Error.setGeometry(QtCore.QRect(380, 620, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.shoppingCart_label_Error.setFont(font)
        self.shoppingCart_label_Error.setStyleSheet("QLabel {\n"
"    color: rgb(180, 43, 29);\n"
"    font: 12pt \"Segoe UI\", \"Arial\", sans-serif;  /* Clean, modern font */\n"
"    letter-spacing: 0.2px;       /* Subtle spacing for readability */\n"
"}")
        self.shoppingCart_label_Error.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.shoppingCart_label_Error.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.shoppingCart_label_Error.setObjectName("shoppingCart_label_Error")
        shoppingCart_MainWindow.setCentralWidget(self.shoppingCart_centralwidget)

        self.retranslateUi(shoppingCart_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(shoppingCart_MainWindow)

    def retranslateUi(self, shoppingCart_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        shoppingCart_MainWindow.setWindowTitle(_translate("shoppingCart_MainWindow", "Ngyopify : Shopping Cart"))
        self.shoppingCart_label_shoppingCart.setText(_translate("shoppingCart_MainWindow", "Shopping Cart"))
        self.shoppingCart_label_shoppingCart.setProperty("aaaa", _translate("shoppingCart_MainWindow", "sa"))
        self.shoppingCart_pushButton_back.setText(_translate("shoppingCart_MainWindow", "Back"))
        self.shoppingCart_tableWidget_shoppingCart.setSortingEnabled(False)
        self.shoppingCart_pushButton_removeItem.setText(_translate("shoppingCart_MainWindow", "Remove Item"))
        self.shoppingCart_pushButton_placeOrder.setText(_translate("shoppingCart_MainWindow", "Place Order"))
        self.shoppingCart_label_totalAmount.setText(_translate("shoppingCart_MainWindow", "Total Amount: ₱ 0000000.00"))
        self.shoppingCart_label_totalAmount.setProperty("aaaa", _translate("shoppingCart_MainWindow", "sa"))
        self.shoppingCart_label_Error.setText(_translate("shoppingCart_MainWindow", ""))
        self.shoppingCart_label_Error.setProperty("aaaa", _translate("shoppingCart_MainWindow", "sa"))
